'use strict';
// Banco 27 letras x25 (1 autor + 3 conjugaciones + 21 definiciones). Respuestas 1 palabra, minúsculas (con eñe).
module.exports = {
  "A": [
    { q: "Cineasta español director de películas como \"Mujeres al borde de un ataque de nervios\" o \"Todo sobre mi madre\"", a: "almodovar" },
    { q: "Primera persona del plural del presente de subjuntivo del verbo amar", a: "amemos" },
    { q: "Segunda persona del singular del pretérito perfecto simple de andar", a: "anduviste" },
    { q: "Tercera persona del singular del condicional simple del verbo amar", a: "amaria" },
    { q: "Perteneciente o relativo a las abejas", a: "apicola" },
    { q: "Dejar desierto o desamparado un lugar o a una persona", a: "abandonar" },
    { q: "Disminuir la cantidad, intensidad o fuerza de algo", a: "apaciguar" },
    { q: "Cerrar o ajustar una prenda ciñéndola con botones, broches o corchetes", a: "abotonar" },
    { q: "Hacer que algo quede abierto o al descubierto", a: "abrir" },
    { q: "Apretar a alguien fuertemente con los brazos en señal de afecto", a: "abrazar" },
    { q: "Dar calor a una persona o cosa para mantenerla templada", a: "abrigar" },
    { q: "Cansar o fastidiar por ser pesado o no ofrecer interés", a: "aburrir" },
    { q: "Llegar a un lugar o acercarse a él", a: "acceder" },
    { q: "Líquido graso de color verde amarillento que se obtiene de la aceituna", a: "aceite" },
    { q: "Fruto del olivo", a: "aceituna" },
    { q: "Poner más rápida la marcha o el movimiento de una cosa", a: "acelerar" },
    { q: "Terminar, dar fin a algo", a: "acabar" },
    { q: "Recibir o admitir voluntariamente lo que se da, ofrece o encarga", a: "aceptar" },
    { q: "Tener costumbre o hábito de hacer algo", a: "acostumbrar" },
    { q: "Acción y efecto de actuar en un espectáculo o escenario", a: "actuacion" },
    { q: "Dar a algo forma o aspecto actual o moderno", a: "actualizar" },
    { q: "Decir o manifestar que alguien es autor de un delito o culpa", a: "acusar" },
    { q: "Situar, colocar a alguien o algo en el lugar conveniente", a: "acomodar" },
    { q: "Persona que profesa la abogacía", a: "abogado" },
    { q: "Insecto himenóptero que produce cera y miel", a: "abeja" },
  ],
  "B": [
    { q: "Compositor y pianista alemán, figura clave del Clasicismo y Romanticismo, autor de la Novena Sinfonía", a: "beethoven" },
    { q: "Tercera persona del singular del presente de indicativo del verbo beber", a: "bebe" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de bailar", a: "bailabamos" },
    { q: "Segunda persona del singular del presente de imperativo del verbo barrer", a: "barre" },
    { q: "Mueble largo sobre el cual pueden sentarse varias personas", a: "banco" },
    { q: "Embarcación de estructura cóncava, de madera, hierro u otro material, capaz de flotar en el agua", a: "barco" },
    { q: "Dar calor a un líquido hasta que se formen burbujas y pase a estado gaseoso", a: "bullir" },
    { q: "Que tiene bondad, en su significado moral o de buena calidad", a: "bueno" },
    { q: "Arma blanca ofensiva de hoja corta y ancha que suele rematarse en punta", a: "bayoneta" },
    { q: "Pieza de tela sujeta a un asta o palo que representa a una nación o comunidad", a: "bandera" },
    { q: "Calzado que resguarda el pie y parte de la pierna", a: "bota" },
    { q: "Establecimiento comercial donde se expenden bebidas que se toman allí mismo", a: "bar" },
    { q: "Cosa no verdadera dicha con intención de engañar", a: "bulo" },
    { q: "Aparato que se pone en la boca del caballo para gobernarlo", a: "bocado" },
    { q: "Tropa o cuadrilla de gente armada o amotinada", a: "bando" },
    { q: "Movimiento del cuerpo al compás de la música", a: "baile" },
    { q: "Hacer que un cuerpo baje o descienda a un lugar inferior", a: "bajar" },
    { q: "Lavar o mojar todo el cuerpo o parte de él en agua u otro líquido", a: "banar" },
    { q: "Tocar una persona o cosa con los labios en señal de amor, amistad o respeto", a: "besar" },
    { q: "Mover la mano abierta o el pañuelo para despedir a alguien o saludar", a: "bracear" },
    { q: "Hacer mofa o burla de algo o de alguien", a: "burlar" },
    { q: "Hacer diligencias para encontrar a alguien o algo", a: "buscar" },
    { q: "Acción de lanzar o despedir saliva por la boca", a: "bocanada" },
    { q: "Persona dedicada a apagar incendios y prestar socorro en siniestros", a: "bombero" },
    { q: "Aparato para elevar agua u otro líquido o para extraer aire", a: "bomba" },
  ],
  "C": [
    { q: "Escritor español del Siglo de Oro, autor de Don Quijote de la Mancha", a: "cervantes" },
    { q: "Primera persona del singular del presente de indicativo de comer", a: "como" },
    { q: "Tercera persona del singular del pretérito imperfecto de indicativo de cantar", a: "cantaba" },
    { q: "Primera persona del plural del presente de indicativo de correr", a: "corremos" },
    { q: "Edificio o sitio destinado a la habitación y vivienda de las personas", a: "casa" },
    { q: "Vehículo de cuatro ruedas para circular por tierra accionado por motor", a: "coche" },
    { q: "Animal solípedo doméstico que sirve de montura y tiro", a: "caballo" },
    { q: "Mamífero rumiante de pelo espeso, cuernos huecos y barbilla", a: "cabra" },
    { q: "Parte superior del cuerpo humano y superior o anterior de muchos animales", a: "cabeza" },
    { q: "Sendero estrecho abierto en el campo o la montaña", a: "camino" },
    { q: "Prenda de vestir que cubre el torso, con cuello, mangas y botones delanteros", a: "camisa" },
    { q: "Mueble para dormir o descansar acostado", a: "cama" },
    { q: "Emitir sonidos melodiosos y modulados con la voz humana", a: "cantar" },
    { q: "Población donde reside el gobierno de una nación o provincia", a: "capital" },
    { q: "Obra teatral o cinematográfica de carácter festivo y desenlace feliz", a: "comedia" },
    { q: "Sentimiento de pena o lástima hacia quien sufre una desgracia", a: "compasion" },
    { q: "Dar forma a algo juntando sus distintas partes", a: "componer" },
    { q: "Adquirir algo a cambio de dinero", a: "comprar" },
    { q: "Tener una opinión o parecer igual al de otra persona", a: "coincidir" },
    { q: "Acompañar a una persona para protegerla o guiarla en el camino", a: "custodiar" },
    { q: "Revestimiento duro que protege el cuerpo de ciertos animales", a: "coraza" },
    { q: "Color de la sangre fresca o del tomate maduro", a: "carmesi" },
    { q: "Aparato que produce sonido al comprimir una perilla de goma", a: "corneta" },
    { q: "Lugar donde se encierra al ganado por la noche", a: "corral" },
    { q: "Fruta redonda y pequeña de color rojo oscuro con hueso leñoso", a: "cereza" },
  ],
  "D": [
    { q: "Pintor surrealista español célebre por La persistencia de la memoria", a: "dali" },
    { q: "Tercera persona del singular del presente de indicativo de dar", a: "da" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de dormir", a: "dormiamos" },
    { q: "Segunda persona del singular del presente de indicativo de decir", a: "dices" },
    { q: "Pieza ósea dura engastada en las mandíbulas que sirve para masticar", a: "diente" },
    { q: "Cada una de las cinco partes terminales de la mano o del pie", a: "dedo" },
    { q: "Moneda corriente o conjunto de bienes que sirve como medio de pago", a: "dinero" },
    { q: "Séptimo y último día de la semana civil", a: "domingo" },
    { q: "Animal mamífero cetáceo muy inteligente que vive en aguas templadas", a: "delfin" },
    { q: "Sensación molesta y aflictiva de una parte del cuerpo", a: "dolor" },
    { q: "Lugar arenoso, seco y desprovisto de vegetación continua", a: "desierto" },
    { q: "Primera comida del día que se toma por la mañana", a: "desayuno" },
    { q: "Ser supremo creador del universo según las religiones monoteístas", a: "dios" },
    { q: "Tiempo que la Tierra tarda en dar una vuelta completa sobre su eje", a: "dia" },
    { q: "Mueble con cajones para guardar ropa de uso personal", a: "despacho" },
    { q: "Mamífero rumiante parecido al ciervo con manchas blancas en el lomo", a: "dama" },
    { q: "Juego de azar que se practica arrojando pequeños cubos numerados", a: "dados" },
    { q: "Perteneciente o relativo al hogar o a la vida de familia", a: "domestico" },
    { q: "Colina o elevación de arena formada por el viento junto al mar o en desiertos", a: "duna" },
    { q: "Lugar donde se despachan medicinas y productos de higiene", a: "drogueria" },
    { q: "Soberano o señor que tiene dominio sobre un territorio", a: "duque" },
    { q: "Persona que tiene por oficio cuidar o arreglar los dientes", a: "dentista" },
    { q: "Que no tiene duda o que está probado de forma concluyente", a: "demostrable" },
    { q: "Espacio de diez años", a: "decada" },
    { q: "Acción y efecto de dejar caer o arrojar algo desde lo alto", a: "derrumbamiento" },
  ],
  "E": [
    { q: "Dramaturgo griego de la antigüedad clásica autor de Las troyanas y Medea", a: "euripides" },
    { q: "Tercera persona del singular del presente de indicativo de esperar", a: "espera" },
    { q: "Primera persona del plural del pretérito perfecto simple de entrar", a: "entramos" },
    { q: "Segunda persona del singular del presente de indicativo de escribir", a: "escribes" },
    { q: "Mamífero paquidermo de gran tamaño provisto de trompa prensil y colmillos", a: "elefante" },
    { q: "Superficie de cristal azogado que refleja la luz y las imágenes", a: "espejo" },
    { q: "Arma blanca larga, recta y cortante con guarnición y empuñadura", a: "espada" },
    { q: "Aparato portátil para proyectar luz formado por una bombilla y pila", a: "escaner" },
    { q: "Conjunto de escalones que enlazan dos planos a distinto nivel", a: "escalera" },
    { q: "Mueble con estantes horizontales destinado a colocar libros u objetos", a: "estante" },
    { q: "Astro del firmamento que brilla con luz propia durante la noche", a: "estrella" },
    { q: "Embarcación provista de motor y quilla que navega a vela o máquina", a: "esquife" },
    { q: "Cosa que sirve de modelo o tipo digno de ser imitado", a: "ejemplo" },
    { q: "Fuerza armada encargada de la defensa militar del territorio nacional", a: "ejercito" },
    { q: "Conjunto de personas que forman un grupo de trabajo o deporte", a: "equipo" },
    { q: "Sitio o paraje donde se detienen temporalmente personas o tropas", a: "estacion" },
    { q: "Aparato receptor que capta y reproduce señales de televisión o radio", a: "emisor" },
    { q: "Persona enviada a otra parte para transmitir un recado o misión", a: "emisario" },
    { q: "Pieza plana de metal con punta en un extremo que sirve para clavar", a: "escarpia" },
    { q: "Aparato con aspas que gira para mover o renovar el aire en una estancia", a: "extractor" },
    { q: "Obra de arte hecha tallando piedra o modelando arcilla o bronce", a: "escultura" },
    { q: "Persona dedicada a escribir libros u obras literarias", a: "escritor" },
    { q: "Sentimiento de admiración mezclado con sorpresa o desconcierto", a: "estupor" },
    { q: "Parte del esqueleto formada por la columna y las costillas", a: "espinazo" },
    { q: "Conjunto de cerdas atadas a un cabo que sirve para barrer el suelo", a: "escoba" },
  ],
  "F": [
    { q: "Cineasta italiano director de obras maestras como La dolce vita, Ocho y medio y Amarcord", a: "fellini" },
    { q: "Tercera persona del singular del presente de indicativo de fijar", a: "fija" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de fumar", a: "fumabamos" },
    { q: "Segunda persona del singular del presente de indicativo de flotar", a: "flotas" },
    { q: "Fenómeno térmico y luminoso producido por la combustión rápida de una materia", a: "fuego" },
    { q: "Luz grande y potente que llevan los vehículos en su parte delantera", a: "faro" },
    { q: "Mamífero carnívoro marino con extremidades en forma de aleta adaptado al nado", a: "foca" },
    { q: "Planta de tallo largo rematado por una flor vistosa y aromática", a: "flor" },
    { q: "Pieza delgada y alargada de madera o cera con cabeza inflamable para encender fuego", a: "fosforo" },
    { q: "Moneda oficial compartida por Suiza y Liechtenstein", a: "franco" },
    { q: "Fruta pequeña, roja, dulce y aromática que crece en matas silvestres", a: "fresa" },
    { q: "Parte superior de la cara humana comprendida entre las cejas y el nacimiento del pelo", a: "frente" },
    { q: "Instrumento musical de viento formado por un tubo con agujeros que se tocan con los dedos", a: "flauta" },
    { q: "Edificio o torre alta con luz en la cúspide para guiar a los navegantes de noche", a: "farola" },
    { q: "Lugar donde se despachan y preparan medicamentos y remedios", a: "farmacia" },
    { q: "Lazo o cinta con que se adorna el pelo o un vestido", a: "floco" },
    { q: "Arma arrojadiza compuesta por un astil con punta afilada que se dispara con arco", a: "flecha" },
    { q: "Conjunto de barcos que navegan juntos o pertenecen a una misma compañía o armada", a: "flota" },
    { q: "Conducto que da salida al humo producido por la combustión en un hogar", a: "fogon" },
    { q: "Hoja de papel doblada que sirve para folletos o avisos", a: "folleto" },
    { q: "Fuerza física que se opone al movimiento entre dos superficies en contacto", a: "friccion" },
    { q: "Parte más honda o inferior de algo hueco como un vaso o un pozo", a: "fondo" },
    { q: "Estado de la atmósfera en que la temperatura baja de cero grados y hiela", a: "frio" },
    { q: "Límite o línea que separa dos estados o términos territoriales", a: "frontera" },
    { q: "Cosa falsa, fingida o imitada para engañar a alguien", a: "fraude" },
  ],
  "G": [
    { q: "Pintor español precursor del arte contemporáneo autor de Los fusilamientos del 3 de mayo", a: "goya" },
    { q: "Tercera persona del singular del presente de indicativo de girar", a: "gira" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de ganar", a: "ganabamos" },
    { q: "Segunda persona del singular del presente de indicativo de gritar", a: "gritas" },
    { q: "Mamífero carnívoro doméstico de uñas retráctiles y ojos adaptados a la oscuridad", a: "gato" },
    { q: "Ave palmípeda doméstica parecida al pato pero de mayor tamaño y cuello largo", a: "ganso" },
    { q: "Fruta esférica de piel rojiza llena de granos jugosos y semillas duras", a: "granada" },
    { q: "Pieza de tela con que se cubre la cabeza para abrigo sin visera ni ala", a: "gorro" },
    { q: "Prenda de tela con visera para resguardar la cabeza del sol", a: "gorra" },
    { q: "Aparato que flota en el aire al llenarse con gas más ligero o aire caliente", a: "globo" },
    { q: "Persona fornida que combatía en los circos de la antigua Roma", a: "gladiador" },
    { q: "Ave rapaz de plumaje pardo ceniciento parecida al halcón", a: "gavilan" },
    { q: "Ave marina de plumaje blanco y gris con pico robusto y pies palmeados", a: "gaviota" },
    { q: "Porción globular de líquido que se desprende o gotea lentamente", a: "gota" },
    { q: "Lucha armada prolongada entre dos o más naciones o facciones", a: "guerra" },
    { q: "Instrumento musical de cuerda pulsada con caja abombada y seis cuerdas", a: "guitarra" },
    { q: "Pieza de tela o piel que cubre la mano ajustándose a cada dedo", a: "guante" },
    { q: "Planta herbácea leguminosa que da semillas verdes y redondas comestibles", a: "guisante" },
    { q: "Armazón de rejas de hierro que cierra una abertura o ventana", a: "garita" },
    { q: "Local cerrado y cubierto destinado a guardar vehículos automóviles", a: "garaje" },
    { q: "Mamífero antropomorfo de gran talla originario de los bosques africanos", a: "gorila" },
    { q: "Parte externa anterior del cuello debajo de la mandíbula", a: "garganta" },
    { q: "Pequeña masa redonda formada por cereales u otros ingredientes", a: "galleta" },
    { q: "Pieza curvada de metal u otro material que sirve para colgar cosas", a: "gancho" },
    { q: "Sustancia adiposa que forma tejido en los animales y grasas vegetales", a: "grasa" },
  ],
  "H": [
    { q: "Cineasta británico maestro del suspense y director de Psicosis y La ventana indiscreta", a: "hitchcock" },
    { q: "Segunda persona del singular del presente de indicativo de hacer", a: "haces" },
    { q: "Tercera persona del singular del pretérito perfecto simple de haber", a: "hubo" },
    { q: "Primera persona del plural del presente de indicativo de hablar", a: "hablamos" },
    { q: "Instrumento cortante compuesto de una hoja gruesa de acero y mango de madera para cortar leña", a: "hacha" },
    { q: "Lugar destinado a la atención, diagnóstico y tratamiento de enfermos o heridos", a: "hospital" },
    { q: "Mueble de lona o red colgado por los extremos para descansar o dormir al aire libre", a: "hamaca" },
    { q: "Alimento dulce elaborado a base de leche, zumo de frutas o agua congelada", a: "helado" },
    { q: "Planta vivaz gramínea que crece en los prados y sirve de pasto al ganado", a: "hierba" },
    { q: "Elemento químico metálico, tenaz, magnético y de color gris plateado", a: "hierro" },
    { q: "Fruto dulce del higueral de forma achatada, pulpa blanda y muchas pepitas", a: "higo" },
    { q: "Organismo eucariota heterótrofo carente de clorofila como la seta o la trufa", a: "hongo" },
    { q: "Conjunto de personas vinculadas por parentesco que viven juntas en una vivienda", a: "hogar" },
    { q: "Insecto social himenóptero que vive en colonias subterráneas muy organizadas", a: "hormiga" },
    { q: "Aparato cerrado que produce calor para cocinar alimentos, cocer barro o fundir metales", a: "horno" },
    { q: "Mamífero carnívoro de pelaje grisáceo adaptado a la caza nocturna en madrigueras", a: "huron" },
    { q: "Mamífero carnívoro de África y Asia de lomo inclinado y fuertes mandíbulas que emite una risa característica", a: "hiena" },
    { q: "Viento impetuoso de extraordinaria fuerza que gira en grandes círculos y produce tempestades", a: "huracan" },
    { q: "Polvo fino que se obtiene moliendo trigo u otros granos de cereal", a: "harina" },
    { q: "Parte delantera de la cabeza del caballo y otros mamíferos", a: "hocico" },
    { q: "Señal o marca que deja el pie del hombre o la pata del animal al pisar el suelo", a: "huella" },
    { q: "Terreno cercado de corta extensión donde se cultivan verduras, legumbres y frutas", a: "huerto" },
    { q: "Espacio de tierra que pertenece a una sola propiedad rural", a: "heredad" },
    { q: "Persona nacida del mismo padre y de la misma madre respecto de otra", a: "hermano" },
    { q: "Objeto de hierro u otro material resistente con que se ejecutan trabajos manuales o mecánicos", a: "herramienta" },
  ],
  "I": [
    { q: "Dramaturgo noruego maestro del drama realista contemporáneo y autor de Casa de muñecas", a: "ibsen" },
    { q: "Primera persona del singular del presente de indicativo de ir", a: "iba" },
    { q: "Segunda persona del singular del presente de indicativo de inventar", a: "inventas" },
    { q: "Tercera persona del singular del pretérito perfecto simple de invadir", a: "invadio" },
    { q: "Templo o edificio consagrado al culto y oración comunitaria de la fe cristiana", a: "iglesia" },
    { q: "Bloque enorme de hielo flotante desprendido de una masa polar que navega a la deriva", a: "iceberg" },
    { q: "Reptil escamoso de cuerpo robusto y cresta espinosa que habita en zonas tropicales", a: "iguana" },
    { q: "Pieza de mineral o metal magnetizada capaz de atraer hacia sí limaduras y objetos férricos", a: "iman" },
    { q: "Extensión territorial o superficie de tierra rodeada de agua por todas sus orillas", a: "isla" },
    { q: "Vivienda tradicional de forma redondeada construida con bloques de hielo prensado por los pueblos esquimales", a: "iglu" },
    { q: "Estación del año comprendida entre el otoño y la primavera caracterizada por el frío riguroso", a: "invierno" },
    { q: "Animal invertebrado de cuerpo segmentado que posee tres pares de patas y antenas", a: "insecto" },
    { q: "Representación visual o mental de un objeto mediante la pintura, escultura o reflejo de la luz", a: "imagen" },
    { q: "Facultad psíquica por la que se proyectan o conciben escenas, figuras e ideas inexistentes", a: "imaginacion" },
    { q: "Aparato que imprime caracteres tipográficos o gráficos sobre papel u otro soporte", a: "impresora" },
    { q: "Tributo o cuota pecuniaria exigida por el Estado a los ciudadanos para sostener los servicios públicos", a: "impuesto" },
    { q: "Falta total o escasez de conocimientos en materia cultural, científica o general", a: "ignorancia" },
    { q: "Lugar por donde se penetra o se accede al interior de un edificio o estancia", a: "ingreso" },
    { q: "Materia o dispositivo que prende y combustiona para despedir un aroma perfumado al arder", a: "incienso" },
    { q: "Marca o reproducción de letras y dibujos sobre una superficie mediante presión entintada", a: "impresion" },
    { q: "Conjunto organizado de signos orales y escritos propios de una colectividad para comunicarse", a: "idioma" },
    { q: "Construcción civil fabril donde se procesan materias primas y se fabrican bienes en serie", a: "industria" },
    { q: "Aparato que produce frío mediante la absorción de calor por evaporación de un fluido", a: "invernadero" },
    { q: "Efecto o consecuencia producida por un golpe brusco o una conmoción repentina", a: "impacto" },
    { q: "Moneda o unidad fiduciaria que se usa legalmente para los pagos en un país soberano", a: "imperio" },
  ],
  "J": [
    { q: "Escritor irlandés clave de la narrativa del siglo XX, autor de Ulises y Dublineses", a: "joyce" },
    { q: "Retirar a una persona del servicio activo tras cumplir los años fijados con pensión vitalicia", a: "jubilar" },
    { q: "Tercera persona del singular del presente de indicativo de jugar", a: "juega" },
    { q: "Primera persona del plural del pretérito perfecto simple de juntar", a: "juntamos" },
    { q: "Animal mamífero rumiante africano de cuello y patas extraordinariamente largos", a: "jirafa" },
    { q: "Mamífero carnívoro félido americano de pelaje amarillento con manchas negras en forma de roseta", a: "jaguar" },
    { q: "Mamífero artiodáctilo salvaje parecido al cerdo de cuerpo robusto y colmillos salientes", a: "jabali" },
    { q: "Sustancia sólida o líquida que resulta de la saponificación de grasas y sirve para lavar", a: "jabon" },
    { q: "Recipiente de barro, loza o cristal con una sola asa y boca ancha para servir líquidos", a: "jarra" },
    { q: "Vaso cilíndrico o abombado más alto que ancho que sirve para adornar o contener flores cortadas", a: "jarron" },
    { q: "Terreno acotado donde se cultivan flores, plantas ornamentales y árboles para recreo", a: "jardin" },
    { q: "Persona que tiene por oficio cuidar y cultivar jardines", a: "jardinero" },
    { q: "Cosa pequeña hecha de metal precioso o pedrería que sirve de adorno personal", a: "joya" },
    { q: "Persona que fabrica, arregla o comercia con joyas y piedras preciosas", a: "joyero" },
    { q: "Pierna trasera de cerdo curada en salazón y secada al aire", a: "jamon" },
    { q: "Armazón de barrotes de alambre o madera en que se encierran aves u otros animales", a: "jaula" },
    { q: "Dolor de cabeza intenso y recurrente que suele afectar a una sola mitad del cráneo", a: "jaqueca" },
    { q: "Planta vivaz medicinal de tallos lisos y flores de olor agradable usada en perfumería", a: "jazmin" },
    { q: "Prenda gruesa de punto con mangas que cubre el torso hasta las caderas", a: "jersey" },
    { q: "Instrumento de cristal o plástico cilíndrico con émbolo para aspirar o inyectar líquidos", a: "jeringa" },
    { q: "Persona que tiene autoridad superior o mandato sobre un grupo o empresa", a: "jefe" },
    { q: "Caballero que corre y monta caballos en carreras públicas", a: "jockey" },
    { q: "Tiempo libre dedicado a la diversión o pasatiempo", a: "juego" },
    { q: "Lugar donde se administra justicia o tribunal unipersonal de un magistrado", a: "juzgado" },
    { q: "Persona que administra justicia y dicta sentencia en un tribunal", a: "juez" },
  ],
  "K": [
    { q: "Escritor checo en lengua alemana, cumbre de la literatura universal, autor de La metamorfosis y El proceso", a: "kafka" },
    { q: "Fruta de piel parda y vellosa con pulpa verde esmeralda y pequeñas semillas negras comestibles", a: "kiwi" },
    { q: "Mamífero marsupial australiano de pelaje gris ceniza y orejas peludas que come hojas de eucalipto", a: "koala" },
    { q: "Unidad de masa del Sistema Internacional equivalente a mil gramos", a: "kilogramo" },
    { q: "Unidad de longitud del Sistema Internacional equivalente a mil metros", a: "kilometro" },
    { q: "Unidad de potencia eléctrica equivalente a mil vatios", a: "kilovatio" },
    { q: "Unidad de energía térmica equivalente a mil calorías", a: "kilocaloria" },
    { q: "Túnica tradicional japonesa de mangas anchas abrochada en la cintura con una faja ancha", a: "kimono" },
    { q: "Piloto militar japonés que tripulaba un avión cargado de explosivos para estrellarlo contra el blanco", a: "kamikaze" },
    { q: "Arte marcial tradicional de origen japonés practicado a manos vacías con golpes secos y patadas", a: "karate" },
    { q: "Pequeño vehículo de cuatro ruedas sin suspensión ni carrocería usado en pistas de competición cerradas", a: "kart" },
    { q: "Embarcación ligera de remo usada por los esquimales totalmente cerrada con una abertura central", a: "kayak" },
    { q: "Salsa espesa y agridulce condimentada elaborada principalmente a base de puré de tomate y vinagre", a: "ketchup" },
    { q: "Movimiento artístico y de diseño de gusto recargado, vulgar o pretencioso", a: "kitsch" },
    { q: "Bebida fermentada originaria del Cáucaso hecha con granos de bacterias lácticas y leche de cabra o vaca", a: "kefir" },
    { q: "Bebida alcohólica tradicional de los cosacos obtenida por fermentación de cereales o pan negro", a: "kvas" },
    { q: "Arte marcial tradicional japonés donde se combate con espadas de bambú y armadura acolchada", a: "kendo" },
    { q: "Prenda o falda plisada tradicional de lana tartán que usan los hombres en las Highlands escocesas", a: "kilt" },
    { q: "Comida callejera de origen turco consistente en carne de cordero asada en un espetón vertical giratorio", a: "kebab" },
    { q: "Granja colectiva y cooperativa agrícola establecida durante la Unión Soviética", a: "koljos" },
    { q: "Moneda oficial utilizada en el archipiélago de Papúa Nueva Guinea", a: "kina" },
    { q: "Juego de mesa semejante a la lotería en que se tapan números impresos en cartones", a: "keno" },
    { q: "Tercera persona del singular del presente de indicativo de hackear", a: "hackea" },
    { q: "Primera persona del plural del presente de indicativo de hackear", a: "hackeamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de hackear", a: "hackearon" },
  ],
  "L": [
    { q: "Poeta y dramaturgo español del Siglo de Oro, el Fénix de los ingenios, autor de Fuenteovejuna", a: "lope" },
    { q: "Animal mamífero carnívoro félido africano de gran tamaño, conocido como el rey de la selva", a: "leon" },
    { q: "Mamífero carnívoro cánido salvaje que vive y caza en manadas territoriales", a: "lobo" },
    { q: "Mamífero carnívoro félido de orejas puntiagudas terminadas en pincel de pelos y cola corta", a: "lince" },
    { q: "Animal mamífero roedor salvaje de patas traseras muy largas y orejas grandes que corre a gran velocidad", a: "liebre" },
    { q: "Mamífero artiodáctilo rumiante propio de la cordillera de los Andes utilizado como animal de carga", a: "llama" },
    { q: "Gusano anélido de cuerpo cilíndrico dividido en anillos que vive enterrado en tierra húmeda", a: "lombriz" },
    { q: "Reptil sauro pequeño y ágil de cuerpo alargado y cola quebradiza que se alimenta de insectos", a: "lagartija" },
    { q: "Reptil de mayor tamaño que la lagartija con escamas ásperas y cabeza triangular", a: "lagarto" },
    { q: "Pez marino teleósteo de carne muy apreciada, lomo grisáceo y vientre plateado", a: "lubina" },
    { q: "Pez marino de cuerpo aplanado y alargado que nada sinuoso entre las rocas costeras", a: "lenguado" },
    { q: "Astro satélite natural de la Tierra que gira a su alrededor reflejando la luz del Sol", a: "luna" },
    { q: "Agente físico que hace visibles los objetos iluminándolos en la oscuridad", a: "luz" },
    { q: "Gran masa de agua dulce depositada de forma natural en hondonadas del terreno", a: "lago" },
    { q: "Masa de agua marina o salobre acumulada tras una barrera de arena o arrecife", a: "laguna" },
    { q: "Masa de roca fundida y ardiente que arrojan los volcanes durante sus erupciones", a: "lava" },
    { q: "Piedra plana, delgada y lisa usada habitualmente para solar suelos o cubrir sepulcros", a: "laja" },
    { q: "Materia blanda y viscosa que resulta de mezclarse la tierra del suelo con agua", a: "lodo" },
    { q: "Piedra fina y preciosa de tono azul ultramar muy valorada en la antigüedad", a: "lapislazuli" },
    { q: "Piedra rectangular plana labrada que se coloca sobre una fosa funeraria con inscripciones", a: "lapida" },
    { q: "Planta de huerto de hojas grandes, blandas y comestibles que se suelen tomar crudas en ensalada", a: "lechuga" },
    { q: "Fruta cítrica de color amarillo brillante, corteza aromática y pulpa muy ácida", a: "limon" },
    { q: "Tercera persona del singular del presente de indicativo de hablar", a: "habla" },
    { q: "Tercera persona del singular del pretérito imperfecto de indicativo de hablar", a: "hablaba" },
    { q: "Tercera persona del plural del pretérito perfecto simple de bailar", a: "bailaron" },
  ],
  "M": [
    { q: "Pintor francés impresionista, maestro de la luz y creador de la serie Nenúfares", a: "monet" },
    { q: "Tercera persona del singular del presente de indicativo de mirar", a: "mira" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de mover", a: "moviamos" },
    { q: "Segunda persona del singular del presente de indicativo de mandar", a: "mandas" },
    { q: "Mamífero primate no humano que posee cola y extremidades ágiles para trepar árboles", a: "mono" },
    { q: "Insecto díptero molesto de cuerpo negro y alas transparentes que acude a la comida", a: "mosca" },
    { q: "Insecto díptero hembra que pica y chupa la sangre del ser humano zumbando en la noche", a: "mosquito" },
    { q: "Mamífero carnívoro de la familia de los mustélidos que arroja un líquido hediondo al sentirse en peligro", a: "mofeta" },
    { q: "Animal mamífero carnívoro marino con colmillos largos de marfil que habita en los mares polares", a: "morsa" },
    { q: "Mamífero rumiante de montaña con pelaje espeso y cuernos curvados hacia atrás", a: "muflon" },
    { q: "Animal híbrido estéril nacido del cruce entre asno y yegua o caballo y asna", a: "mula" },
    { q: "Ave rapaz diurna de cola bifurcada y vuelo sostenido que caza presas campestres", a: "milano" },
    { q: "Molusco bivalvo de concha oscura y ovalada muy abundante adherido a las rocas marinas", a: "mejillon" },
    { q: "Masa de agua salada que cubre más del setenta por ciento del globo terráqueo", a: "mar" },
    { q: "Gran elevación natural del terreno de altura considerable sobre el plano circundante", a: "montana" },
    { q: "Extensión considerable de tierra poblada densamente de árboles y maleza silvestre", a: "monte" },
    { q: "Terreno bajo y pantanoso que se inunda habitualmente por las aguas del mar o de los ríos", a: "marisma" },
    { q: "Mineral metamórfico compacto formado por calizas cristalizadas muy apreciado en escultura", a: "marmol" },
    { q: "Mineral de silicato de alúmina que se exfolia fácilmente en láminas transparentes", a: "mica" },
    { q: "Lugar costero cerrado artificialmente con diques para fondear y resguardar embarcaciones", a: "muelle" },
    { q: "Fruta redonda de pulpa carnosa dulce o ácida con semillas menudas en el corazón", a: "manzana" },
    { q: "Fruto carnoso de piel rojiza y vellosa con un hueso rugoso central y pulpa muy jugosa", a: "melocoton" },
    { q: "Fruta veraniega grande de corteza verde y pulpa dulce y acuosa con muchas pepitas", a: "melon" },
    { q: "Fruta tropical de pulpa amarilla o anaranjada muy jugosa y hueso fibroso y aplanado", a: "mango" },
    { q: "Fruto cítrico parecido a la naranja pero más pequeño y de cáscara fácil de pelar", a: "mandarina" },
  ],
  "N": [
    { q: "Poeta y diplomático chileno galardonado con el Premio Nobel de Literatura en 1971, autor de Veinte poemas de amor y una canción desesperada", a: "neruda" },
    { q: "Tercera persona del singular del presente de indicativo de nadar", a: "nada" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de navegar", a: "navegabamos" },
    { q: "Segunda persona del singular del presente de indicativo de necesitar", a: "necesitas" },
    { q: "Mamífero carnívoro acuático de cola gruesa y pelaje pardo impermeable que nada en ríos y lagos", a: "nutria" },
    { q: "Cetáceo marino de los mares árticos cuyo macho posee un colmillo largo y retorcido en espiral", a: "narval" },
    { q: "Fruto del nogal de cáscara leñosa y dura que contiene una semilla comestible arrugada", a: "nuez" },
    { q: "Fruta cítrica dulce de corteza anaranjada y pulpa dividida en gajos jugosos", a: "naranja" },
    { q: "Fruto del níspero de color amarillento, pulpa carnosa dulce con semillas grandes marrones", a: "nispero" },
    { q: "Masa visible de vapor acuoso suspendida en la atmósfera producida por condensación", a: "nube" },
    { q: "Agua congelada que cae de las nubes en copos blancos cristalizados", a: "nieve" },
    { q: "Masa de vapor de agua muy espesa a ras de suelo o de mar que reduce notablemente la visibilidad", a: "niebla" },
    { q: "Embarcación marina de gran porte movida por velas o propulsión mecánica", a: "nave" },
    { q: "Vehículo submarino o de superficie tripulado que sirve para navegar por las aguas", a: "navio" },
    { q: "Instrumento cortante de bolsillo cuya hoja de acero se pliega dentro del mango", a: "navaja" },
    { q: "Espacio de tiempo que transcurre desde que se pone el Sol hasta que amanece", a: "noche" },
    { q: "Parte saliente de la cara humana entre los ojos y la boca donde reside el olfato", a: "nariz" },
    { q: "Articulación donde se unen los huesos de los dedos en la mano que resalta al cerrar el puño", a: "nudillo" },
    { q: "Lugar formado por ramas o paja que construyen las aves para poner huevos y criar a sus polluelos", a: "nido" },
    { q: "Parte posterior del cuello humano donde la cabeza se une a la columna vertebral", a: "nuca" },
    { q: "Expresión o signo gráfico que indica una cantidad o valor aritmético", a: "numero" },
    { q: "Nombre con que se designa o reconoce formalmente a una persona, animal o cosa", a: "nombre" },
    { q: "Decimoprimero mes del año natural que cuenta con treinta días", a: "noviembre" },
    { q: "Persona que se halla en relaciones amorosas previas al matrimonio formal con otra", a: "novio" },
    { q: "Obra literaria en prosa de extensión considerable que relata sucesos fingidos o reales", a: "novela" },
  ],
  "Ñ": [
    { q: "Escritor español autor de El invierno en Lisboa", a: "muñoz" },
    { q: "Tercera persona del singular del presente de indicativo de arañar", a: "araña" },
    { q: "Primera persona del plural del presente de indicativo de arañar", a: "arañamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de arañar", a: "arañaron" },
    { q: "Día que sigue a hoy", a: "mañana" },
    { q: "Fruto seco que comen las ardillas", a: "piñones" },
    { q: "Etapa cuando eres niño pequeño", a: "niñez" },
    { q: "Persona de pocos años", a: "niño" },
    { q: "Tela para sonarse la nariz", a: "pañuelo" },
    { q: "Casa pequeña en el campo", a: "cabaña" },
    { q: "Madera para hacer fuego", a: "leña" },
    { q: "Pelo pequeño del párpado", a: "pestaña" },
    { q: "Monte muy grande", a: "montaña" },
    { q: "Anuncio para vender algo", a: "campaña" },
    { q: "Empresa de varias personas", a: "compañia" },
    { q: "De poco tamaño", a: "pequeño" },
    { q: "Lo que ves al dormir", a: "sueño" },
    { q: "El propietario de algo", a: "dueño" },
    { q: "Hermano de tu esposo o esposa", a: "cuñado" },
    { q: "Dulce frito con azúcar", a: "buñuelo" },
    { q: "Tela para bebés", a: "pañal" },
    { q: "Para lavarse", a: "baño" },
    { q: "Doce meses", a: "año" },
    { q: "Niño femenino", a: "niña" },
    { q: "Afecto", a: "cariño" },
  ],
  "O": [
    { q: "Filósofo español autor de La rebelión de las masas", a: "ortega" },
    { q: "Primera persona del singular del presente de indicativo de tomar", a: "tomo" },
    { q: "Primera persona del plural del presente de indicativo de tomar", a: "tomamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de correr", a: "corrieron" },
    { q: "Parte del cuerpo para ver", a: "ojo" },
    { q: "Metal precioso amarillo de los anillos", a: "oro" },
    { q: "Animal grande que duerme en invierno", a: "oso" },
    { q: "Parte externa del oído", a: "oreja" },
    { q: "Onda grande del mar", a: "ola" },
    { q: "Árbol del que sale la aceituna", a: "olivo" },
    { q: "Recipiente para cocinar", a: "olla" },
    { q: "Lugar donde se trabaja con papeles", a: "oficina" },
    { q: "Lo que se percibe por la nariz", a: "olor" },
    { q: "Cosa material que se puede tocar", a: "objeto" },
    { q: "Trabajo de arte o construcción", a: "obra" },
    { q: "Sin luz, contrario de claro", a: "oscuro" },
    { q: "Que ocupa el lugar número ocho", a: "octavo" },
    { q: "Venta a buen precio", a: "oferta" },
    { q: "Borde del mar o del río", a: "orilla" },
    { q: "Satisfacción por algo propio", a: "orgullo" },
    { q: "Estación entre el verano y el invierno", a: "otoño" },
    { q: "Obra de teatro cantada", a: "opera" },
    { q: "Colocación de las cosas en su sitio", a: "orden" },
    { q: "Conjunto de músicos con instrumentos", a: "orquesta" },
    { q: "Cicatriz redonda en el vientre", a: "ombligo" },
  ],
  "P": [
    { q: "Pintor español creador del cubismo y del Guernica", a: "picasso" },
    { q: "Primera persona del plural del pretérito perfecto simple de romper", a: "rompimos" },
    { q: "Primera persona del plural del presente de indicativo de comprar", a: "compramos" },
    { q: "Tercera persona del singular del presente de indicativo de romper", a: "rompe" },
    { q: "Comida que se hace con harina", a: "pan" },
    { q: "Animal que ladra y mueve la cola", a: "perro" },
    { q: "Abertura para entrar en una casa", a: "puerta" },
    { q: "Trozo de roca dura", a: "piedra" },
    { q: "Población pequeña", a: "pueblo" },
    { q: "Construcción para cruzar un río", a: "puente" },
    { q: "Hijo de tu tío", a: "primo" },
    { q: "Lugar con agua para nadar", a: "piscina" },
    { q: "Historia que se ve en el cine", a: "pelicula" },
    { q: "Instrumento de teclas blancas y negras", a: "piano" },
    { q: "Pelo suave de las aves", a: "pluma" },
    { q: "Orilla del mar con arena", a: "playa" },
    { q: "Espacio abierto en un pueblo", a: "plaza" },
    { q: "Recipiente para comer", a: "plato" },
    { q: "Dinero que cuesta algo", a: "precio" },
    { q: "Cuestión para saber algo", a: "pregunta" },
    { q: "Estación de las flores", a: "primavera" },
    { q: "Dulce de cumpleaños con velas", a: "pastel" },
    { q: "Objeto para no mojarse con la lluvia", a: "paraguas" },
    { q: "Prenda para cubrir las piernas", a: "pantalon" },
    { q: "Fruta amarilla curva de los monos", a: "platano" },
  ],
  "Q": [
    { q: "Escritor español del Siglo de Oro autor de El Buscón", a: "quevedo" },
    { q: "Primera persona del plural del presente de indicativo de quedar", a: "quedamos" },
    { q: "Primera persona del singular del presente de subjuntivo de buscar", a: "busque" },
    { q: "Tercera persona del plural del presente de subjuntivo de tocar", a: "toquen" },
    { q: "Comida amarilla con agujeros que gusta a los ratones", a: "queso" },
    { q: "Puesto pequeño en la calle", a: "quiosco" },
    { q: "Después del cuarto", a: "quinto" },
    { q: "Ciencia de las sustancias", a: "quimica" },
    { q: "Después del catorce", a: "quince" },
    { q: "Sin moverse ni hacer ruido", a: "quieto" },
    { q: "Falta de ruido", a: "quietud" },
    { q: "Rotura de un negocio", a: "quiebra" },
    { q: "Grupo de cinco músicos", a: "quinteto" },
    { q: "Herida por fuego", a: "quemadura" },
    { q: "Lamento por algo", a: "queja" },
    { q: "Persona amada", a: "querido" },
    { q: "Ave de plumaje verde de América", a: "quetzal" },
    { q: "Sala de operaciones", a: "quirofano" },
    { q: "Peso de cien kilos", a: "quintal" },
    { q: "Tarea doméstica", a: "quehacer" },
    { q: "Cariño a un lugar", a: "querencia" },
    { q: "Parte donde gira la puerta", a: "quicio" },
    { q: "Pago de quince días", a: "quincena" },
    { q: "Boleto de apuestas de fútbol", a: "quiniela" },
    { q: "Bulto en el cuerpo", a: "quiste" },
  ],
  "R": [
    { q: "Pintor holandés autor de La ronda de noche", a: "rembrandt" },
    { q: "Primera persona del plural del presente de indicativo de mirar", a: "miramos" },
    { q: "Tercera persona del plural del presente de indicativo de mirar", a: "miran" },
    { q: "Tercera persona del plural del pretérito perfecto simple de cantar", a: "cantaron" },
    { q: "Flor roja símbolo del amor", a: "rosa" },
    { q: "Animal que salta y dice croac", a: "rana" },
    { q: "Corriente de agua", a: "rio" },
    { q: "Círculo para girar", a: "rueda" },
    { q: "Prenda de vestir", a: "ropa" },
    { q: "Aparato para saber la hora", a: "reloj" },
    { q: "Malla para pescar", a: "red" },
    { q: "El de la corona", a: "rey" },
    { q: "Esposa del rey", a: "reina" },
    { q: "Animal pequeño con bigotes", a: "raton" },
    { q: "Parte del árbol con hojas", a: "rama" },
    { q: "Lugar para comer fuera", a: "restaurante" },
    { q: "Contestación a una pregunta", a: "respuesta" },
    { q: "Sonido molesto", a: "ruido" },
    { q: "Hueso de la pierna", a: "rodilla" },
    { q: "Piedra grande", a: "roca" },
    { q: "Árbol de bellotas", a: "roble" },
    { q: "Color de la sangre", a: "rojo" },
    { q: "Juego de casino con bola", a: "ruleta" },
    { q: "Falta leve", a: "roce" },
    { q: "Camino rural", a: "rodera" },
  ],
  "S": [
    { q: "Dramaturgo inglés autor de Hamlet", a: "shakespeare" },
    { q: "Primera persona del plural del presente de indicativo de ser", a: "somos" },
    { q: "Segunda persona del singular del presente de indicativo de cantar", a: "cantas" },
    { q: "Primera persona del plural del presente de indicativo de comer", a: "comemos" },
    { q: "Astro que da luz de día", a: "sol" },
    { q: "Mueble para sentarse", a: "silla" },
    { q: "Mueble largo del salón", a: "sofa" },
    { q: "Animal parecido a la rana", a: "sapo" },
    { q: "Hongo comestible", a: "seta" },
    { q: "Siete días", a: "semana" },
    { q: "Bosque tropical", a: "selva" },
    { q: "Lo que se planta", a: "semilla" },
    { q: "Montañas en fila", a: "sierra" },
    { q: "Líquido rojo del cuerpo", a: "sangre" },
    { q: "Buen estado del cuerpo", a: "salud" },
    { q: "Cosa oculta", a: "secreto" },
    { q: "Sin peligro", a: "seguro" },
    { q: "Después del primero", a: "segundo" },
    { q: "Animal que se arrastra sin patas", a: "serpiente" },
    { q: "Gesto alegre con la boca", a: "sonrisa" },
    { q: "Para la cabeza contra el sol", a: "sombrero" },
    { q: "Comida líquida caliente", a: "sopa" },
    { q: "Pez pequeño de lata", a: "sardina" },
    { q: "Día antes del domingo", a: "sabado" },
    { q: "Arena del desierto", a: "siroco" },
  ],
  "T": [
    { q: "Escritor ruso autor de Guerra y paz", a: "tolstoi" },
    { q: "Primera persona del plural del presente de indicativo de cantar", a: "cantamos" },
    { q: "Segunda persona del singular del presente de indicativo de saltar", a: "saltas" },
    { q: "Primera persona del plural del presente de indicativo de votar", a: "votamos" },
    { q: "Dulce de cumpleaños con velas", a: "tarta" },
    { q: "Instrumento que se toca con baquetas", a: "tambor" },
    { q: "Vehículo amarillo con taxímetro", a: "taxi" },
    { q: "Animal con cuernos", a: "toro" },
    { q: "Felino con rayas", a: "tigre" },
    { q: "Recipiente para café", a: "taza" },
    { q: "Aparato para llamar", a: "telefono" },
    { q: "Caja con imágenes", a: "television" },
    { q: "Lugar con escenario", a: "teatro" },
    { q: "Parte alta de la casa", a: "techo" },
    { q: "Barra blanca para pizarra", a: "tiza" },
    { q: "Para cortar papel", a: "tijera" },
    { q: "Fruto rojo de ensalada", a: "tomate" },
    { q: "Animal lento con caparazón", a: "tortuga" },
    { q: "Vehículo sobre raíles", a: "tren" },
    { q: "Tallo grueso del árbol", a: "tronco" },
    { q: "Ruido del rayo", a: "trueno" },
    { q: "Parte del día antes de la noche", a: "tarde" },
    { q: "Deberes del cole", a: "tarea" },
    { q: "Planeta donde vivimos", a: "tierra" },
    { q: "Tela fuerte azul", a: "tejano" },
  ],
  "U": [
    { q: "Escritor español autor de Niebla", a: "unamuno" },
    { q: "Tercera persona del singular del pretérito perfecto simple de poder", a: "pudo" },
    { q: "Tercera persona del plural del presente de indicativo de subir", a: "suben" },
    { q: "Primera persona del plural del presente de indicativo de cruzar", a: "cruzamos" },
    { q: "Fruta pequeña en racimo", a: "uva" },
    { q: "Número primero", a: "uno" },
    { q: "El final", a: "ultimo" },
    { q: "Que corre prisa", a: "urgente" },
    { q: "Solo en su especie", a: "unico" },
    { q: "Ropa igual para todos", a: "uniforme" },
    { q: "Junta de dos cosas", a: "union" },
    { q: "Lugar de estudios superiores", a: "universidad" },
    { q: "Parte dura del dedo", a: "uña" },
    { q: "Entrada de una casa", a: "umbral" },
    { q: "Pájaro blanco y negro", a: "urraca" },
    { q: "Caballo con un cuerno", a: "unicornio" },
    { q: "Tienda de comestibles", a: "ultramarinos" },
    { q: "Caja para votos", a: "urna" },
    { q: "Persona que usa algo", a: "usuario" },
    { q: "Herramienta de cocina", a: "utensilio" },
    { q: "Nombre de la letra ve", a: "uve" },
    { q: "Puerta del hospital", a: "urgencias" },
    { q: "De segunda mano", a: "usado" },
    { q: "Que sirve", a: "util" },
    { q: "Cada una de las partes", a: "unidad" },
  ],
  "V": [
    { q: "Pintor español autor de Las Meninas", a: "velazquez" },
    { q: "Primera persona del plural del presente de indicativo de vivir", a: "vivimos" },
    { q: "Segunda persona del singular del presente de indicativo de volver", a: "vuelves" },
    { q: "Tercera persona del singular del presente de indicativo de llover", a: "llueve" },
    { q: "Animal que da leche y dice mu", a: "vaca" },
    { q: "Bebida de uvas", a: "vino" },
    { q: "Barco con velas", a: "velero" },
    { q: "Para beber agua", a: "vaso" },
    { q: "Abertura con cristal", a: "ventana" },
    { q: "Estación del calor", a: "verano" },
    { q: "Color de la hierba", a: "verde" },
    { q: "Prenda de vestir", a: "vestido" },
    { q: "Salida lejos", a: "viaje" },
    { q: "Aire en movimiento", a: "viento" },
    { q: "Cilindro de cera con mecha", a: "vela" },
    { q: "El de al lado", a: "vecino" },
    { q: "Pinchazo contra enfermedades", a: "vacuna" },
    { q: "Parte del tren", a: "vagon" },
    { q: "Entre montañas", a: "valle" },
    { q: "Agua en el aire", a: "vapor" },
    { q: "Lo contrario de mentira", a: "verdad" },
    { q: "Pena por algo mal", a: "verguenza" },
    { q: "Armario de cristal", a: "vitrina" },
    { q: "Montaña que echa lava", a: "volcan" },
    { q: "Ir a ver a alguien", a: "visita" },
  ],
  "W": [
    { q: "Cineasta estadounidense director de Ciudadano Kane", a: "welles" },
    { q: "Tercera persona del singular del presente de indicativo de wasapear", a: "wasapea" },
    { q: "Primera persona del plural del presente de indicativo de wasapear", a: "wasapeamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de wasapear", a: "wasapearon" },
    { q: "Red de páginas de internet", a: "web" },
    { q: "Red sin cables", a: "wifi" },
    { q: "Deporte en piscina con balón", a: "waterpolo" },
    { q: "Película del oeste", a: "western" },
    { q: "Deporte con tabla y vela", a: "windsurf" },
    { q: "Sartén honda oriental", a: "wok" },
    { q: "Metal para bombillas", a: "wolframio" },
    { q: "Excusado", a: "water" },
    { q: "Aparato para hablar a distancia", a: "walkie" },
    { q: "Tienda de indios", a: "wigwam" },
    { q: "Arte marcial chino", a: "wushu" },
    { q: "Programas del ordenador", a: "software" },
    { q: "Partes del ordenador", a: "hardware" },
    { q: "Espectáculo", a: "show" },
    { q: "Vaquero del oeste", a: "cowboy" },
    { q: "Tabla para la nieve", a: "snowboard" },
    { q: "Unidad de fuerza", a: "newton" },
    { q: "Bocadillo con dos panes", a: "sandwich" },
    { q: "Capital de Estados Unidos", a: "washington" },
    { q: "Músico alemán autor del Anillo", a: "wagner" },
    { q: "Color blanco en inglés", a: "white" },
  ],
  "X": [
    { q: "Historiador griego autor de la Anábasis", a: "xenofonte" },
    { q: "Tercera persona del singular del presente de indicativo de explicar", a: "explica" },
    { q: "Primera persona del plural del presente de indicativo de examinar", a: "examinamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de extraer", a: "extrajeron" },
    { q: "Prueba del cole con preguntas", a: "examen" },
    { q: "Deporte de guantes", a: "boxeo" },
    { q: "Instrumento dorado de jazz", a: "saxofon" },
    { q: "Después del quinto", a: "sexto" },
    { q: "Escrito para leer", a: "texto" },
    { q: "De otro país", a: "extranjero" },
    { q: "Café rápido", a: "expreso" },
    { q: "Parte alargada", a: "extension" },
    { q: "De fuera", a: "exterior" },
    { q: "De más", a: "extra" },
    { q: "Brazo o pierna", a: "extremidad" },
    { q: "Vivir fuera del país", a: "exilio" },
    { q: "Que sabe mucho", a: "experto" },
    { q: "Ruido grande con fuego", a: "explosion" },
    { q: "Viaje corto", a: "excursion" },
    { q: "Triunfo", a: "exito" },
    { q: "Gas para respirar", a: "oxigeno" },
    { q: "Piso de dos plantas", a: "duplex" },
    { q: "Difícil", a: "mixto" },
    { q: "Unión de dos cosas", a: "nexo" },
    { q: "Vocabulario", a: "lexico" },
  ],
  "Y": [
    { q: "Poeta irlandés premio Nobel autor de La torre", a: "yeats" },
    { q: "Primera persona del singular del presente de subjuntivo de haber", a: "haya" },
    { q: "Primera persona del singular del presente de subjuntivo de ir", a: "vaya" },
    { q: "Tercera persona del plural del pretérito perfecto simple de oír", a: "oyeron" },
    { q: "Deporte de estiramiento", a: "yoga" },
    { q: "Barco blanco de lujo", a: "yate" },
    { q: "Parte amarilla del huevo", a: "yema" },
    { q: "Postre de leche", a: "yogur" },
    { q: "Hembra del caballo", a: "yegua" },
    { q: "Blanco para escayola", a: "yeso" },
    { q: "Para curar heridas", a: "yodo" },
    { q: "Planta tropical", a: "yuca" },
    { q: "Para forjar hierro", a: "yunque" },
    { q: "Mina subterránea", a: "yacimiento" },
    { q: "Juguete que sube y baja", a: "yoyo" },
    { q: "Pareja de bueyes", a: "yunta" },
    { q: "Desierto", a: "yermo" },
    { q: "Que practica yoga", a: "yogui" },
    { q: "Toro castrado", a: "buey" },
    { q: "Fibra textil", a: "yute" },
    { q: "Estadounidense", a: "yanqui" },
    { q: "Medida de tierra", a: "yugada" },
    { q: "Comida", a: "yantar" },
    { q: "País árabe", a: "yemen" },
    { q: "Yo existo", a: "soy" },
  ],
  "Z": [
    { q: "Escritor francés autor de Germinal", a: "zola" },
    { q: "Primera persona del singular del presente de indicativo de cruzar", a: "cruzo" },
    { q: "Primera persona del plural del presente de indicativo de gozar", a: "gozamos" },
    { q: "Tercera persona del singular del presente de indicativo de empezar", a: "empieza" },
    { q: "Bebida de naranja exprimida", a: "zumo" },
    { q: "Animal astuto de cola grande", a: "zorro" },
    { q: "Arbusto con espinas", a: "zarza" },
    { q: "Para los pies", a: "zapato" },
    { q: "Mosquito", a: "zancudo" },
    { q: "Agujero largo", a: "zanja" },
    { q: "El que arregla zapatos", a: "zapatero" },
    { q: "Teatro cantado español", a: "zarzuela" },
    { q: "Lugar con animales", a: "zoologico" },
    { q: "Zapato de madera", a: "zueco" },
    { q: "Ruido de abeja", a: "zumbido" },
    { q: "Que usa la izquierda", a: "zurdo" },
    { q: "Nombre de la última letra", a: "zeta" },
    { q: "Línea quebrada", a: "zigzag" },
    { q: "Piedra azul", a: "zafiro" },
    { q: "Verdura naranja", a: "zanahoria" },
    { q: "Parte baja de la pared", a: "zocalo" },
    { q: "Torpe y lento", a: "zoquete" },
    { q: "Muchacho", a: "zagal" },
    { q: "Chaqueta de piel", a: "zamarra" },
    { q: "Pendiente", a: "zarcillo" },
  ],
};
