'use strict';
// Banco 27 letras x25 (2 autores + 3 conjugaciones + 20 definiciones). Respuestas 1 palabra, minúsculas (con eñe).
module.exports = {
  "A": [
    { q: "Cineasta español director de películas como Mujeres al borde de un ataque", a: "almodovar" },
    { q: "Primera persona del plural del presente de subjuntivo del verbo amar", a: "amemos" },
    { q: "Segunda persona del singular del pretérito perfecto simple de andar", a: "anduviste" },
    { q: "Tercera persona del singular del condicional simple del verbo amar", a: "amaria" },
    { q: "Perteneciente o relativo a las abejas", a: "apicola" },
    { q: "Dejar desierto o desamparado un lugar o a una persona", a: "abandonar" },
    { q: "Disminuir la cantidad, intensidad o fuerza de algo", a: "apaciguar" },
    { q: "Cerrar o ajustar una prenda ciñéndola con botones, broches o corchetes", a: "abotonar" },
    { q: "Hacer que algo quede abierto o al descubierto", a: "abrir" },
    { q: "Apretar a alguien fuertemente con los brazos en señal de afecto", a: "abrazar" },
    { q: "Dar calor a una persona o cosa para mantenerla templada", a: "abrigar" },
    { q: "Cansar o fastidiar por ser pesado o no ofrecer interés", a: "aburrir" },
    { q: "Llegar a un lugar o acercarse a él", a: "acceder" },
    { q: "Líquido graso de color verde amarillento que se obtiene de la aceituna", a: "aceite" },
    { q: "Escritora canadiense contemporánea autora de Alias Grace y El asesino ciego", a: "atwood" },
    { q: "Poner más rápida la marcha o el movimiento de una cosa", a: "acelerar" },
    { q: "Terminar, dar fin a algo", a: "acabar" },
    { q: "Recibir o admitir voluntariamente lo que se da, ofrece o encarga", a: "aceptar" },
    { q: "Tener costumbre o hábito de hacer algo", a: "acostumbrar" },
    { q: "Acción y efecto de actuar en un espectáculo o escenario", a: "actuacion" },
    { q: "Dar a algo forma o aspecto actual o moderno", a: "actualizar" },
    { q: "Decir o manifestar que alguien es autor de un delito o culpa", a: "acusar" },
    { q: "Situar, colocar a alguien o algo en el lugar conveniente", a: "acomodar" },
    { q: "Persona que profesa la abogacía", a: "abogado" },
    { q: "Insecto himenóptero que produce cera y miel", a: "abeja" }
  ],
  "B": [
    { q: "Compositor y pianista alemán, figura clave del Clasicismo y Romanticismo, autor de", a: "beethoven" },
    { q: "Tercera persona del singular del condicional simple del verbo beber", a: "beberia" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de bailar", a: "bailabamos" },
    { q: "Segunda persona del singular del pretérito imperfecto de subjuntivo del verbo barrer", a: "barrieras" },
    { q: "Mueble largo sobre el cual pueden sentarse varias personas", a: "banco" },
    { q: "Escritor argentino del siglo veinte autor de Ficciones y El Aleph", a: "borges" },
    { q: "Dar calor a un líquido hasta que se formen burbujas y pase", a: "bullir" },
    { q: "Que tiene bondad, en su significado moral o de buena calidad", a: "bueno" },
    { q: "Arma blanca ofensiva de hoja corta y ancha que suele rematarse en punta", a: "bayoneta" },
    { q: "Pieza de tela sujeta a un asta o palo que representa a", a: "bandera" },
    { q: "Calzado que resguarda el pie y parte de la pierna", a: "bota" },
    { q: "Establecimiento comercial donde se expenden bebidas que se toman allí mismo", a: "bar" },
    { q: "Cosa no verdadera dicha con intención de engañar", a: "bulo" },
    { q: "Aparato que se pone en la boca del caballo para gobernarlo", a: "bocado" },
    { q: "Tropa o cuadrilla de gente armada o amotinada", a: "bando" },
    { q: "Movimiento del cuerpo al compás de la música", a: "baile" },
    { q: "Hacer que un cuerpo baje o descienda a un lugar inferior", a: "bajar" },
    { q: "Lavar o mojar todo el cuerpo o parte de él en agua", a: "banar" },
    { q: "Tocar una persona o cosa con los labios en señal de amor,", a: "besar" },
    { q: "Mover la mano abierta o el pañuelo para despedir a alguien o saludar", a: "bracear" },
    { q: "Hacer mofa o burla de algo o de alguien", a: "burlar" },
    { q: "Hacer diligencias para encontrar a alguien o algo", a: "buscar" },
    { q: "Acción de lanzar o despedir saliva por la boca", a: "bocanada" },
    { q: "Persona dedicada a apagar incendios y prestar socorro en siniestros", a: "bombero" },
    { q: "Aparato para elevar agua u otro líquido o para extraer aire", a: "bomba" }
  ],
  "C": [
    { q: "Escritor español del Siglo de Oro, autor de Don Quijote de la Mancha", a: "cervantes" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo comer", a: "comiera" },
    { q: "Tercera persona del singular del pretérito imperfecto de indicativo de cantar", a: "cantaba" },
    { q: "Tercera persona del plural del condicional simple del verbo correr", a: "correrian" },
    { q: "Dramaturgo español barroco autor de El alcalde de Zalamea y La dama duende", a: "calderon" },
    { q: "Vehículo de cuatro ruedas para circular por tierra accionado por motor", a: "coche" },
    { q: "Animal solípedo doméstico que sirve de montura y tiro", a: "caballo" },
    { q: "Mamífero rumiante de pelo espeso, cuernos huecos y barbilla", a: "cabra" },
    { q: "Parte superior del cuerpo humano y superior o anterior de muchos animales", a: "cabeza" },
    { q: "Sendero estrecho abierto en el campo o la montaña", a: "camino" },
    { q: "Prenda de vestir que cubre el torso, con cuello, mangas y botones delanteros", a: "camisa" },
    { q: "Mueble para dormir o descansar acostado", a: "cama" },
    { q: "Emitir sonidos melodiosos y modulados con la voz humana", a: "cantar" },
    { q: "Población donde reside el gobierno de una nación o provincia", a: "capital" },
    { q: "Obra teatral o cinematográfica de carácter festivo y desenlace feliz", a: "comedia" },
    { q: "Sentimiento de pena o lástima hacia quien sufre una desgracia", a: "compasion" },
    { q: "Dar forma a algo juntando sus distintas partes", a: "componer" },
    { q: "Adquirir algo a cambio de dinero", a: "comprar" },
    { q: "Tener una opinión o parecer igual al de otra persona", a: "coincidir" },
    { q: "Acompañar a una persona para protegerla o guiarla en el camino", a: "custodiar" },
    { q: "Revestimiento duro que protege el cuerpo de ciertos animales", a: "coraza" },
    { q: "Color de la sangre fresca o del tomate maduro", a: "carmesi" },
    { q: "Aparato que produce sonido al comprimir una perilla de goma", a: "corneta" },
    { q: "Lugar donde se encierra al ganado por la noche", a: "corral" },
    { q: "Fruta redonda y pequeña de color rojo oscuro con hueso leñoso", a: "cereza" }
  ],
  "D": [
    { q: "Pintor surrealista español célebre por La persistencia de la memoria", a: "dali" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo dar", a: "diera" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de dormir", a: "dormiamos" },
    { q: "Segunda persona del singular del condicional simple del verbo decir", a: "dirias" },
    { q: "Pieza ósea dura engastada en las mandíbulas que sirve para masticar", a: "diente" },
    { q: "Cada una de las cinco partes terminales de la mano o del pie", a: "dedo" },
    { q: "Moneda corriente o conjunto de bienes que sirve como medio de pago", a: "dinero" },
    { q: "Séptimo y último día de la semana civil", a: "domingo" },
    { q: "Animal mamífero cetáceo muy inteligente que vive en aguas templadas", a: "delfin" },
    { q: "Sensación molesta y aflictiva de una parte del cuerpo", a: "dolor" },
    { q: "Lugar arenoso, seco y desprovisto de vegetación continua", a: "desierto" },
    { q: "Primera comida del día que se toma por la mañana", a: "desayuno" },
    { q: "Ser supremo creador del universo según las religiones monoteístas", a: "dios" },
    { q: "Tiempo que la Tierra tarda en dar una vuelta completa sobre su eje", a: "dia" },
    { q: "Mueble con cajones para guardar ropa de uso personal", a: "despacho" },
    { q: "Mamífero rumiante parecido al ciervo con manchas blancas en el lomo", a: "dama" },
    { q: "Juego de azar que se practica arrojando pequeños cubos numerados", a: "dados" },
    { q: "Perteneciente o relativo al hogar o a la vida de familia", a: "domestico" },
    { q: "Colina o elevación de arena formada por el viento junto al mar", a: "duna" },
    { q: "Lugar donde se despachan medicinas y productos de higiene", a: "drogueria" },
    { q: "Soberano o señor que tiene dominio sobre un territorio", a: "duque" },
    { q: "Persona que tiene por oficio cuidar o arreglar los dientes", a: "dentista" },
    { q: "Que no tiene duda o que está probado de forma concluyente", a: "demostrable" },
    { q: "Escritor inglés victoriano autor de Tiempos difíciles y Barnaby Rudge", a: "dickens" },
    { q: "Acción y efecto de dejar caer o arrojar algo desde lo alto", a: "derrumbamiento" }
  ],
  "E": [
    { q: "Dramaturgo griego de la antigüedad clásica autor de Las troyanas y Medea", a: "euripides" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo esperar", a: "esperara" },
    { q: "Primera persona del plural del pretérito perfecto simple de entrar", a: "entramos" },
    { q: "Segunda persona del singular del condicional simple del verbo escribir", a: "escribirias" },
    { q: "Mamífero paquidermo de gran tamaño provisto de trompa prensil y colmillos", a: "elefante" },
    { q: "Superficie de cristal azogado que refleja la luz y las imágenes", a: "espejo" },
    { q: "Arma blanca larga, recta y cortante con guarnición y empuñadura", a: "espada" },
    { q: "Aparato portátil para proyectar luz formado por una bombilla y pila", a: "escaner" },
    { q: "Conjunto de escalones que enlazan dos planos a distinto nivel", a: "escalera" },
    { q: "Compositor inglés romántico autor de Variaciones Enigma y Marchas de pompa", a: "elgar" },
    { q: "Astro del firmamento que brilla con luz propia durante la noche", a: "estrella" },
    { q: "Embarcación provista de motor y quilla que navega a vela o máquina", a: "esquife" },
    { q: "Cosa que sirve de modelo o tipo digno de ser imitado", a: "ejemplo" },
    { q: "Fuerza armada encargada de la defensa militar del territorio nacional", a: "ejercito" },
    { q: "Conjunto de personas que forman un grupo de trabajo o deporte", a: "equipo" },
    { q: "Sitio o paraje donde se detienen temporalmente personas o tropas", a: "estacion" },
    { q: "Aparato receptor que capta y reproduce señales de televisión o radio", a: "emisor" },
    { q: "Persona enviada a otra parte para transmitir un recado o misión", a: "emisario" },
    { q: "Pieza plana de metal con punta en un extremo que sirve para clavar", a: "escarpia" },
    { q: "Aparato con aspas que gira para mover o renovar el aire en una estancia", a: "extractor" },
    { q: "Obra de arte hecha tallando piedra o modelando arcilla o bronce", a: "escultura" },
    { q: "Persona dedicada a escribir libros u obras literarias", a: "escritor" },
    { q: "Sentimiento de admiración mezclado con sorpresa o desconcierto", a: "estupor" },
    { q: "Parte del esqueleto formada por la columna y las costillas", a: "espinazo" },
    { q: "Conjunto de cerdas atadas a un cabo que sirve para barrer el suelo", a: "escoba" }
  ],
  "F": [
    { q: "Cineasta italiano director de obras maestras como La dolce vita, Ocho y", a: "fellini" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo fijar", a: "fijara" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de fumar", a: "fumabamos" },
    { q: "Segunda persona del singular del condicional simple del verbo flotar", a: "flotarias" },
    { q: "Fenómeno térmico y luminoso producido por la combustión rápida de una materia", a: "fuego" },
    { q: "Luz grande y potente que llevan los vehículos en su parte delantera", a: "faro" },
    { q: "Mamífero carnívoro marino con extremidades en forma de aleta adaptado al nado", a: "foca" },
    { q: "Escritor francés realista autor de La educación sentimental y Bouvard", a: "flaubert" },
    { q: "Pieza delgada y alargada de madera o cera con cabeza inflamable para encender fuego", a: "fosforo" },
    { q: "Moneda oficial compartida por Suiza y Liechtenstein", a: "franco" },
    { q: "Fruta pequeña, roja, dulce y aromática que crece en matas silvestres", a: "fresa" },
    { q: "Parte superior de la cara humana comprendida entre las cejas y el", a: "frente" },
    { q: "Instrumento musical de viento formado por un tubo con agujeros que se", a: "flauta" },
    { q: "Edificio o torre alta con luz en la cúspide para guiar a", a: "farola" },
    { q: "Lugar donde se despachan y preparan medicamentos y remedios", a: "farmacia" },
    { q: "Lazo o cinta con que se adorna el pelo o un vestido", a: "floco" },
    { q: "Arma arrojadiza compuesta por un astil con punta afilada que se dispara con arco", a: "flecha" },
    { q: "Conjunto de barcos que navegan juntos o pertenecen a una misma compañía o armada", a: "flota" },
    { q: "Conducto que da salida al humo producido por la combustión en un hogar", a: "fogon" },
    { q: "Hoja de papel doblada que sirve para propaganda o avisos", a: "folleto" },
    { q: "Fuerza física que se opone al movimiento entre dos superficies en contacto", a: "friccion" },
    { q: "Parte más honda o inferior de algo hueco como un vaso o un pozo", a: "fondo" },
    { q: "Estado de la atmósfera en que la temperatura baja de cero grados y hiela", a: "frio" },
    { q: "Límite o línea que separa dos estados o términos territoriales", a: "frontera" },
    { q: "Cosa falsa, fingida o imitada para engañar a alguien", a: "fraude" }
  ],
  "G": [
    { q: "Pintor español precursor del arte contemporáneo autor de Los fusilamientos", a: "goya" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo girar", a: "girara" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de ganar", a: "ganabamos" },
    { q: "Segunda persona del singular del condicional simple del verbo gritar", a: "gritarias" },
    { q: "Mamífero carnívoro doméstico de uñas retráctiles y ojos adaptados a la oscuridad", a: "gato" },
    { q: "Ave palmípeda doméstica parecida al pato pero de mayor tamaño y cuello largo", a: "ganso" },
    { q: "Fruta esférica de piel rojiza llena de granos jugosos y semillas duras", a: "granada" },
    { q: "Pieza de tela con que se cubre la cabeza para abrigo sin", a: "gorro" },
    { q: "Prenda de tela con visera para resguardar la cabeza del sol", a: "gorra" },
    { q: "Aparato que flota en el aire al llenarse con gas más ligero", a: "globo" },
    { q: "Persona fornida que combatía en los circos de la antigua Roma", a: "gladiador" },
    { q: "Ave rapaz de plumaje pardo ceniciento parecida al halcón", a: "gavilan" },
    { q: "Ave marina de plumaje blanco y gris con pico robusto y pies palmeados", a: "gaviota" },
    { q: "Porción globular de líquido que se desprende o gotea lentamente", a: "gota" },
    { q: "Lucha armada prolongada entre dos o más naciones o facciones", a: "guerra" },
    { q: "Instrumento musical de cuerda pulsada con caja abombada y seis cuerdas", a: "guitarra" },
    { q: "Pieza de tela o piel que cubre la mano ajustándose a cada dedo", a: "guante" },
    { q: "Planta herbácea leguminosa que da semillas verdes y redondas comestibles", a: "guisante" },
    { q: "Armazón de rejas de hierro que cierra una abertura o ventana", a: "garita" },
    { q: "Local cerrado y cubierto destinado a guardar vehículos automóviles", a: "garaje" },
    { q: "Mamífero antropomorfo de gran talla originario de los bosques africanos", a: "gorila" },
    { q: "Parte externa anterior del cuello debajo de la mandíbula", a: "garganta" },
    { q: "Pequeña masa redonda formada por cereales u otros ingredientes", a: "galleta" },
    { q: "Pieza curvada de metal u otro material que sirve para colgar cosas", a: "gancho" },
    { q: "Novelista español decimonónico autor de Misericordia y Nazarín", a: "galdos" }
  ],
  "H": [
    { q: "Cineasta británico maestro del suspense y director de Psicosis y La ventana indiscreta", a: "hitchcock" },
    { q: "Segunda persona del singular del condicional simple del verbo hacer", a: "harias" },
    { q: "Tercera persona del singular del pretérito perfecto simple de haber", a: "hubo" },
    { q: "Primera persona del plural del pretérito imperfecto de subjuntivo del verbo hablar", a: "hablaramos" },
    { q: "Escritor estadounidense del siglo veinte autor de Por quién doblan y Adiós", a: "hemingway" },
    { q: "Lugar destinado a la atención, diagnóstico y tratamiento de enfermos o heridos", a: "hospital" },
    { q: "Mueble de lona o red colgado por los extremos para descansar o", a: "hamaca" },
    { q: "Alimento dulce elaborado a base de leche, zumo de frutas o agua congelada", a: "helado" },
    { q: "Planta vivaz gramínea que crece en los prados y sirve de pasto al ganado", a: "hierba" },
    { q: "Elemento químico metálico, tenaz, magnético y de color gris plateado", a: "hierro" },
    { q: "Fruto dulce del higueral de forma achatada, pulpa blanda y muchas pepitas", a: "higo" },
    { q: "Organismo eucariota heterótrofo carente de clorofila como la seta o la trufa", a: "hongo" },
    { q: "Conjunto de personas vinculadas por parentesco que viven juntas en una vivienda", a: "hogar" },
    { q: "Insecto social himenóptero que vive en colonias subterráneas muy organizadas", a: "hormiga" },
    { q: "Aparato cerrado que produce calor para cocinar alimentos, cocer barro o fundir metales", a: "horno" },
    { q: "Mamífero carnívoro de pelaje grisáceo adaptado a la caza nocturna en madrigueras", a: "huron" },
    { q: "Mamífero carnívoro de África y Asia de lomo inclinado y fuertes mandíbulas", a: "hiena" },
    { q: "Viento impetuoso de extraordinaria fuerza que gira en grandes círculos y produce tempestades", a: "huracan" },
    { q: "Polvo fino que se obtiene moliendo trigo u otros granos de cereal", a: "harina" },
    { q: "Parte delantera de la cabeza del caballo y otros mamíferos", a: "hocico" },
    { q: "Señal o marca que deja el pie del hombre o la pata", a: "huella" },
    { q: "Terreno cercado de corta extensión donde se cultivan verduras, legumbres y frutas", a: "huerto" },
    { q: "Espacio de tierra que pertenece a una sola propiedad rural", a: "heredad" },
    { q: "Persona nacida del mismo padre y de la misma madre respecto de otra", a: "hermano" },
    { q: "Objeto de hierro u otro material resistente con que se ejecutan trabajos", a: "herramienta" }
  ],
  "I": [
    { q: "Dramaturgo noruego maestro del drama realista contemporáneo y autor de Casa de muñecas", a: "ibsen" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo inventar", a: "inventara" },
    { q: "Tercera persona del singular del condicional simple del verbo inventar", a: "inventaria" },
    { q: "Tercera persona del singular del pretérito perfecto simple de invadir", a: "invadio" },
    { q: "Templo o edificio consagrado al culto y oración comunitaria de la fe cristiana", a: "iglesia" },
    { q: "Escritor estadounidense romántico autor de Rip Van Winkle y Sleepy Hollow", a: "irving" },
    { q: "Reptil escamoso de cuerpo robusto y cresta espinosa que habita en zonas tropicales", a: "iguana" },
    { q: "Pieza de mineral o metal magnetizada capaz de atraer hacia sí limaduras", a: "iman" },
    { q: "Extensión territorial o superficie de tierra rodeada de agua por todas sus orillas", a: "isla" },
    { q: "Vivienda tradicional de forma redondeada construida con bloques de hielo prensado por", a: "iglu" },
    { q: "Estación del año comprendida entre el otoño y la primavera caracterizada por", a: "invierno" },
    { q: "Animal invertebrado de cuerpo segmentado que posee tres pares de patas y antenas", a: "insecto" },
    { q: "Representación visual o mental de un objeto mediante la pintura, escultura o", a: "imagen" },
    { q: "Facultad psíquica por la que se proyectan o conciben escenas, figuras e ideas inexistentes", a: "imaginacion" },
    { q: "Aparato que imprime caracteres tipográficos o gráficos sobre papel u otro soporte", a: "impresora" },
    { q: "Tributo o cuota pecuniaria exigida por el Estado a los ciudadanos para", a: "impuesto" },
    { q: "Falta total o escasez de conocimientos en materia cultural, científica o general", a: "ignorancia" },
    { q: "Lugar por donde se penetra o se accede al interior de un", a: "ingreso" },
    { q: "Materia o dispositivo que prende y combustiona para despedir un aroma perfumado al arder", a: "incienso" },
    { q: "Marca o reproducción de letras y dibujos sobre una superficie mediante presión entintada", a: "impresion" },
    { q: "Conjunto organizado de signos orales y escritos propios de una colectividad para comunicarse", a: "idioma" },
    { q: "Construcción civil fabril donde se procesan materias primas y se fabrican bienes en serie", a: "industria" },
    { q: "Aparato que produce frío mediante la absorción de calor por evaporación de un fluido", a: "invernadero" },
    { q: "Efecto o consecuencia producida por un golpe brusco o una conmoción repentina", a: "impacto" },
    { q: "Moneda o unidad fiduciaria que se usa legalmente para los pagos en", a: "imperio" }
  ],
  "J": [
    { q: "Escritor irlandés clave de la narrativa del siglo XX, autor de Ulises y Dublineses", a: "joyce" },
    { q: "Poeta español modernista autor de Baladas de primavera y Pastorales", a: "jimenez" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo jugar", a: "jugara" },
    { q: "Primera persona del plural del pretérito perfecto simple de juntar", a: "juntamos" },
    { q: "Animal mamífero rumiante africano de cuello y patas extraordinariamente largos", a: "jirafa" },
    { q: "Mamífero carnívoro félido americano de pelaje amarillento con manchas negras en forma de roseta", a: "jaguar" },
    { q: "Mamífero artiodáctilo salvaje parecido al cerdo de cuerpo robusto y colmillos salientes", a: "jabali" },
    { q: "Sustancia sólida o líquida que resulta de la saponificación de grasas y", a: "jabon" },
    { q: "Recipiente de barro, loza o cristal con una sola asa y boca", a: "jarra" },
    { q: "Vaso cilíndrico o abombado más alto que ancho que sirve para adornar", a: "jarron" },
    { q: "Tercera persona del plural del pretérito imperfecto de subjuntivo del verbo juntar", a: "juntaran" },
    { q: "Persona que tiene por oficio cuidar y cultivar jardines", a: "jardinero" },
    { q: "Cosa pequeña hecha de metal precioso o pedrería que sirve de adorno personal", a: "joya" },
    { q: "Persona que fabrica, arregla o comercia con joyas y piedras preciosas", a: "joyero" },
    { q: "Pierna trasera de cerdo curada en salazón y secada al aire", a: "jamon" },
    { q: "Armazón de barrotes de alambre o madera en que se encierran aves", a: "jaula" },
    { q: "Dolor de cabeza intenso y recurrente que suele afectar a una sola", a: "jaqueca" },
    { q: "Planta vivaz medicinal de tallos lisos y flores de olor agradable usada en perfumería", a: "jazmin" },
    { q: "Prenda gruesa de punto con mangas que cubre el torso hasta las caderas", a: "jersey" },
    { q: "Instrumento de cristal o plástico cilíndrico con émbolo para aspirar o inyectar líquidos", a: "jeringa" },
    { q: "Persona que tiene autoridad superior o mandato sobre un grupo o empresa", a: "jefe" },
    { q: "Caballero que corre y monta caballos en carreras públicas", a: "jockey" },
    { q: "Tiempo libre dedicado a la diversión o pasatiempo", a: "juego" },
    { q: "Lugar donde se administra justicia o tribunal unipersonal de un magistrado", a: "juzgado" },
    { q: "Persona que administra justicia y dicta sentencia en un tribunal", a: "juez" }
  ],
  "K": [
    { q: "Escritor checo en lengua alemana, cumbre de la literatura universal, autor de", a: "kafka" },
    { q: "Pintor suizo expresionista autor de Senecio y Castillo y sol", a: "klee" },
    { q: "Mamífero marsupial australiano de pelaje gris ceniza y orejas peludas que come", a: "koala" },
    { q: "Unidad de masa del Sistema Internacional equivalente a mil gramos", a: "kilogramo" },
    { q: "Unidad de longitud del Sistema Internacional equivalente a mil metros", a: "kilometro" },
    { q: "Unidad de potencia eléctrica equivalente a mil vatios", a: "kilovatio" },
    { q: "Unidad de energía térmica equivalente a mil calorías", a: "kilocaloria" },
    { q: "Túnica tradicional japonesa de mangas anchas abrochada en la cintura con una faja ancha", a: "kimono" },
    { q: "Piloto militar japonés que tripulaba un avión cargado de explosivos para estrellarlo", a: "kamikaze" },
    { q: "Arte marcial tradicional de origen japonés practicado a manos vacías con golpes", a: "karate" },
    { q: "Pequeño vehículo de cuatro ruedas sin suspensión ni carrocería usado en pistas", a: "kart" },
    { q: "Embarcación ligera de remo usada por los esquimales totalmente cerrada con una abertura central", a: "kayak" },
    { q: "Salsa espesa y agridulce condimentada elaborada principalmente a base de puré de", a: "ketchup" },
    { q: "Movimiento artístico y de diseño de gusto recargado, vulgar o pretencioso", a: "kitsch" },
    { q: "Bebida fermentada originaria del Cáucaso hecha con granos de bacterias lácticas y", a: "kefir" },
    { q: "Bebida alcohólica tradicional de los cosacos obtenida por fermentación de cereales o pan negro", a: "kvas" },
    { q: "Arte marcial tradicional japonés donde se combate con espadas de bambú y armadura acolchada", a: "kendo" },
    { q: "Prenda o falda plisada tradicional de lana tartán que usan los hombres", a: "kilt" },
    { q: "Comida callejera de origen turco consistente en carne de cordero asada en", a: "kebab" },
    { q: "Granja colectiva y cooperativa agrícola establecida durante la Unión Soviética", a: "koljos" },
    { q: "Moneda oficial utilizada en el archipiélago de Papúa Nueva Guinea", a: "kina" },
    { q: "Juego de mesa semejante a la lotería en que se tapan números", a: "keno" },
    { q: "Tercera persona del singular del condicional simple del verbo hackear", a: "hackearia" },
    { q: "Primera persona del plural del pretérito imperfecto de subjuntivo del verbo hackear", a: "hackearamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de hackear", a: "hackearon" }
  ],
  "L": [
    { q: "Poeta y dramaturgo español del Siglo de Oro, el Fénix de los", a: "lope" },
    { q: "Poeta español de la generación del veintisiete autor de Diván y Poema del cante", a: "lorca" },
    { q: "Mamífero carnívoro cánido salvaje que vive y caza en manadas territoriales", a: "lobo" },
    { q: "Mamífero carnívoro félido de orejas puntiagudas terminadas en pincel de pelos y cola corta", a: "lince" },
    { q: "Animal mamífero roedor salvaje de patas traseras muy largas y orejas grandes", a: "liebre" },
    { q: "Mamífero artiodáctilo rumiante propio de la cordillera de los Andes utilizado como", a: "llama" },
    { q: "Gusano anélido de cuerpo cilíndrico dividido en anillos que vive enterrado en tierra húmeda", a: "lombriz" },
    { q: "Reptil sauro pequeño y ágil de cuerpo alargado y cola quebradiza que", a: "lagartija" },
    { q: "Reptil de mayor tamaño que la lagartija con escamas ásperas y cabeza triangular", a: "lagarto" },
    { q: "Pez marino teleósteo de carne muy apreciada, lomo grisáceo y vientre plateado", a: "lubina" },
    { q: "Pez marino de cuerpo aplanado y alargado que nada sinuoso entre las rocas costeras", a: "lenguado" },
    { q: "Astro satélite natural de la Tierra que gira a su alrededor reflejando", a: "luna" },
    { q: "Agente que hace visibles objetos lejanos iluminándolos en la oscuridad", a: "luz" },
    { q: "Gran masa de agua dulce depositada de forma natural en hondonadas del terreno", a: "lago" },
    { q: "Masa de agua marina o salobre acumulada tras una barrera de arena o arrecife", a: "laguna" },
    { q: "Masa de roca fundida y ardiente que arrojan los volcanes durante sus erupciones", a: "lava" },
    { q: "Piedra plana, delgada y lisa usada habitualmente para solar suelos o cubrir sepulcros", a: "laja" },
    { q: "Materia blanda y viscosa que resulta de mezclarse la tierra del suelo con agua", a: "lodo" },
    { q: "Piedra fina y preciosa de tono azul ultramar muy valorada en la antigüedad", a: "lapislazuli" },
    { q: "Piedra rectangular plana labrada que se coloca sobre una fosa funeraria con inscripciones", a: "lapida" },
    { q: "Planta de huerto de hojas grandes, blandas y comestibles que se suelen", a: "lechuga" },
    { q: "Fruta cítrica de color amarillo brillante, corteza aromática y pulpa muy ácida", a: "limon" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo hablar", a: "hablara" },
    { q: "Tercera persona del singular del pretérito imperfecto de indicativo de hablar", a: "hablaba" },
    { q: "Tercera persona del plural del pretérito perfecto simple de bailar", a: "bailaron" }
  ],
  "M": [
    { q: "Pintor francés impresionista, maestro de la luz y creador de la serie Nenúfares", a: "monet" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo mirar", a: "mirara" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de mover", a: "moviamos" },
    { q: "Segunda persona del singular del condicional simple del verbo mandar", a: "mandarias" },
    { q: "Mamífero primate no humano que posee cola y extremidades ágiles para trepar árboles", a: "mono" },
    { q: "Insecto díptero molesto de cuerpo negro y alas transparentes que acude a la comida", a: "mosca" },
    { q: "Escritor japonés contemporáneo autor de Kafka en la orilla y After Dark", a: "murakami" },
    { q: "Mamífero carnívoro de la familia de los mustélidos que arroja un líquido", a: "mofeta" },
    { q: "Animal mamífero carnívoro marino con colmillos largos de marfil que habita en", a: "morsa" },
    { q: "Mamífero rumiante de montaña con pelaje espeso y cuernos curvados hacia atrás", a: "muflon" },
    { q: "Animal híbrido estéril nacido del cruce entre asno y yegua o caballo y asna", a: "mula" },
    { q: "Ave rapaz diurna de cola bifurcada y vuelo sostenido que caza presas campestres", a: "milano" },
    { q: "Molusco bivalvo de concha oscura y ovalada muy abundante adherido a las rocas marinas", a: "mejillon" },
    { q: "Masa de agua salada que cubre más del setenta por ciento del globo terráqueo", a: "mar" },
    { q: "Gran elevación natural del terreno de altura considerable sobre el plano circundante", a: "montana" },
    { q: "Extensión considerable de tierra poblada densamente de árboles y maleza silvestre", a: "monte" },
    { q: "Terreno bajo y pantanoso que se inunda habitualmente por las aguas del", a: "marisma" },
    { q: "Mineral metamórfico compacto formado por calizas cristalizadas muy apreciado en escultura", a: "marmol" },
    { q: "Mineral de silicato de alúmina que se exfolia fácilmente en láminas transparentes", a: "mica" },
    { q: "Lugar costero cerrado artificialmente con diques para fondear y resguardar embarcaciones", a: "muelle" },
    { q: "Fruta redonda de pulpa carnosa dulce o ácida con semillas menudas en el corazón", a: "manzana" },
    { q: "Fruto carnoso de piel rojiza y vellosa con un hueso rugoso central", a: "melocoton" },
    { q: "Fruta veraniega grande de corteza verde y pulpa dulce y acuosa con muchas pepitas", a: "melon" },
    { q: "Fruta tropical de pulpa amarilla o anaranjada muy jugosa y hueso fibroso y aplanado", a: "mango" },
    { q: "Fruto cítrico parecido a la naranja pero más pequeño y de cáscara", a: "mandarina" }
  ],
  "N": [
    { q: "Poeta chileno contemporáneo autor de Veinte poemas y Canto general", a: "neruda" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo nadar", a: "nadara" },
    { q: "Primera persona del plural del pretérito imperfecto de indicativo de navegar", a: "navegabamos" },
    { q: "Segunda persona del singular del condicional simple del verbo necesitar", a: "necesitarias" },
    { q: "Mamífero carnívoro acuático de cola gruesa y pelaje pardo impermeable que nada", a: "nutria" },
    { q: "Cetáceo marino de los mares árticos cuyo macho posee un colmillo largo", a: "narval" },
    { q: "Fruto del nogal de cáscara leñosa y dura que contiene una semilla comestible arrugada", a: "nuez" },
    { q: "Escritor ruso exiliado autor de Pálido fuego y Ada o el ardor", a: "nabokov" },
    { q: "Fruto del árbol frutal de color amarillento y pulpa dulce con semillas grandes", a: "nispero" },
    { q: "Masa visible de vapor acuoso suspendida en la atmósfera producida por condensación", a: "nube" },
    { q: "Agua congelada que cae de las nubes en copos blancos cristalizados", a: "nieve" },
    { q: "Masa de vapor de agua muy espesa a ras de suelo o", a: "niebla" },
    { q: "Embarcación marina de gran porte movida por velas o propulsión mecánica", a: "nave" },
    { q: "Vehículo submarino o de superficie tripulado que sirve para navegar por las aguas", a: "navio" },
    { q: "Instrumento cortante de bolsillo cuya hoja de acero se pliega dentro del mango", a: "navaja" },
    { q: "Espacio de tiempo que transcurre desde que se pone el Sol hasta que amanece", a: "noche" },
    { q: "Parte saliente de la cara humana entre los ojos y la boca", a: "nariz" },
    { q: "Articulación donde se unen los huesos de los dedos en la mano", a: "nudillo" },
    { q: "Lugar formado por ramas o paja que construyen las aves para poner", a: "nido" },
    { q: "Parte posterior del cuello humano donde la cabeza se une a la columna vertebral", a: "nuca" },
    { q: "Expresión o signo gráfico que indica una cantidad o valor aritmético", a: "numero" },
    { q: "Término con que se designa o reconoce formalmente a una persona, animal o cosa", a: "nombre" },
    { q: "Decimoprimero mes del año natural que cuenta con treinta días", a: "noviembre" },
    { q: "Persona que se halla en relaciones amorosas previas al matrimonio formal con otra", a: "novio" },
    { q: "Obra literaria en prosa de extensión considerable que relata sucesos fingidos o reales", a: "novela" }
  ],
  "Ñ": [
    { q: "Escritor español autor de El invierno en Lisboa", a: "muñoz" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo arañar", a: "arañara" },
    { q: "Primera persona del plural del condicional simple del verbo arañar", a: "arañariamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de arañar", a: "arañaron" },
    { q: "Día que sigue a hoy", a: "mañana" },
    { q: "Fruto seco que comen las ardillas", a: "piñones" },
    { q: "Etapa cuando eres niño pequeño", a: "niñez" },
    { q: "Persona menuda de pocos años", a: "niño" },
    { q: "Tela para sonarse la nariz", a: "pañuelo" },
    { q: "Casa pequeña en el campo", a: "cabaña" },
    { q: "Madera cortada para alimentar el fuego", a: "leña" },
    { q: "Vello breve del borde del párpado", a: "pestaña" },
    { q: "Elevación grande de terreno con cumbre", a: "montaña" },
    { q: "Anuncio intenso para vender un producto", a: "campaña" },
    { q: "Empresa formada por varios socios", a: "compañia" },
    { q: "De tamaño reducido y poca altura", a: "pequeño" },
    { q: "Lo que ves al dormir", a: "sueño" },
    { q: "Propietario legal de un bien", a: "dueño" },
    { q: "Hermano de tu esposo o esposa", a: "cuñado" },
    { q: "Dulce frito de masa con azúcar", a: "buñuelo" },
    { q: "Prenda absorbente para bebés lactantes", a: "pañal" },
    { q: "Aseo con agua para lavarse entero", a: "baño" },
    { q: "Periodo de doce meses seguidos", a: "año" },
    { q: "Menor femenina de corta edad", a: "niña" },
    { q: "Escritor valenciano de principios del siglo veinte autor de La barraca y Cañas", a: "ibañez" }
  ],
  "O": [
    { q: "Filósofo español autor de La rebelión de las masas", a: "ortega" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo tomar", a: "tomara" },
    { q: "Primera persona del plural del condicional simple del verbo tomar", a: "tomariamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de correr", a: "corrieron" },
    { q: "Parte del cuerpo para ver", a: "ojo" },
    { q: "Metal precioso amarillo de los anillos", a: "oro" },
    { q: "Animal grande que duerme en invierno", a: "oso" },
    { q: "Pliegue cartilaginoso lateral de la cabeza que capta sonidos", a: "oreja" },
    { q: "Masa de agua marina que avanza y rompe contra la orilla", a: "ola" },
    { q: "Árbol del que sale la aceituna", a: "olivo" },
    { q: "Escritor inglés del siglo veinte autor de Sin blanca y Homenaje a Cataluña", a: "orwell" },
    { q: "Lugar donde se trabaja con papeles", a: "oficina" },
    { q: "Lo que se percibe por la nariz", a: "olor" },
    { q: "Cosa material que se puede tocar", a: "objeto" },
    { q: "Trabajo de arte o construcción", a: "obra" },
    { q: "Sin luz, contrario de claro", a: "oscuro" },
    { q: "Que ocupa el lugar número ocho", a: "octavo" },
    { q: "Propuesta comercial ventajosa con precio rebajado por tiempo limitado", a: "oferta" },
    { q: "Borde del mar o del río", a: "orilla" },
    { q: "Satisfacción íntima por un logro propio que cuesta disimular", a: "orgullo" },
    { q: "Estación entre el verano y el invierno", a: "otoño" },
    { q: "Obra escénica cantada con orquesta en un teatro lírico", a: "opera" },
    { q: "Colocación de las cosas en su sitio", a: "orden" },
    { q: "Conjunto de músicos con instrumentos", a: "orquesta" },
    { q: "Cicatriz redonda en el vientre", a: "ombligo" }
  ],
  "P": [
    { q: "Pintor español creador del cubismo y del Guernica", a: "picasso" },
    { q: "Primera persona del plural del pretérito perfecto simple de romper", a: "rompimos" },
    { q: "Primera persona del plural del condicional simple del verbo comprar", a: "comprariamos" },
    { q: "Tercera persona del singular del condicional simple del verbo romper", a: "romperia" },
    { q: "Comida que se hace con harina", a: "pan" },
    { q: "Animal que ladra y mueve la cola", a: "perro" },
    { q: "Abertura para entrar en una casa", a: "puerta" },
    { q: "Fragmento mineral duro que se usa en construcción y muros", a: "piedra" },
    { q: "Escritora gallega naturalista autora de Insolación y Morriña", a: "pardo" },
    { q: "Construcción para cruzar un río", a: "puente" },
    { q: "Hijo del tío carnal con quien se comparte abuelos", a: "primo" },
    { q: "Lugar con agua para nadar", a: "piscina" },
    { q: "Historia que se ve en el cine", a: "pelicula" },
    { q: "Instrumento de teclas blancas y negras", a: "piano" },
    { q: "Pelo suave de las aves", a: "pluma" },
    { q: "Orilla del mar con arena", a: "playa" },
    { q: "Espacio abierto en un pueblo", a: "plaza" },
    { q: "Recipiente llano de cocina donde se sirve la comida", a: "plato" },
    { q: "Cantidad de dinero exigida a cambio de un bien", a: "precio" },
    { q: "Cuestión formulada para obtener una información o aclaración", a: "pregunta" },
    { q: "Estación templada de flores entre el invierno y el estío", a: "primavera" },
    { q: "Dulce de cumpleaños con velas", a: "pastel" },
    { q: "Objeto para no mojarse con la lluvia", a: "paraguas" },
    { q: "Prenda para cubrir las piernas", a: "pantalon" },
    { q: "Fruta amarilla curva de los monos", a: "platano" }
  ],
  "Q": [
    { q: "Escritor español del Siglo de Oro autor de El Buscón", a: "quevedo" },
    { q: "Primera persona del plural del condicional simple del verbo quedar", a: "quedariamos" },
    { q: "Primera persona del singular del presente de subjuntivo de buscar", a: "busque" },
    { q: "Tercera persona del plural del presente de subjuntivo de tocar", a: "toquen" },
    { q: "Comida amarilla con agujeros que gusta a los ratones", a: "queso" },
    { q: "Puesto pequeño en la calle", a: "quiosco" },
    { q: "Lugar ordinal tras el cuarto en una serie ordenada", a: "quinto" },
    { q: "Ciencia de la materia que estudia reacciones y compuestos", a: "quimica" },
    { q: "Número impar tras el catorce y antes del dieciséis", a: "quince" },
    { q: "Sin moverse ni hacer ruido", a: "quieto" },
    { q: "Estado de calma total sin movimiento ni bullicio", a: "quietud" },
    { q: "Colapso económico de un negocio que deja deudas", a: "quiebra" },
    { q: "Conjunto musical de cinco voces o instrumentos afinados", a: "quinteto" },
    { q: "Lesión de la piel causada por fuego o calor intenso", a: "quemadura" },
    { q: "Expresión de disgusto o protesta por un agravio", a: "queja" },
    { q: "Escritor uruguayo modernista autor de Anaconda y El salvaje", a: "quiroga" },
    { q: "Ave de plumaje verde de América", a: "quetzal" },
    { q: "Sala estéril del hospital donde se opera con anestesia", a: "quirofano" },
    { q: "Peso tradicional de cien kilos para mercancías pesadas", a: "quintal" },
    { q: "Ocupación doméstica cotidiana como limpiar o cocinar", a: "quehacer" },
    { q: "Apego afectivo a un lugar donde se vivió", a: "querencia" },
    { q: "Parte donde gira la puerta", a: "quicio" },
    { q: "Periodo de quince días con paga al final", a: "quincena" },
    { q: "Boleto de apuestas de fútbol", a: "quiniela" },
    { q: "Bulto interno bajo la piel con líquido retenido", a: "quiste" }
  ],
  "R": [
    { q: "Pintor holandés autor de La ronda de noche", a: "rembrandt" },
    { q: "Primera persona del plural del condicional simple del verbo mirar", a: "mirariamos" },
    { q: "Tercera persona del plural del pretérito imperfecto de subjuntivo del verbo mirar", a: "miraran" },
    { q: "Tercera persona del plural del pretérito perfecto simple de cantar", a: "cantaron" },
    { q: "Flor roja símbolo del amor", a: "rosa" },
    { q: "Animal que salta y dice croac", a: "rana" },
    { q: "Corriente continua de agua dulce hacia el mar", a: "rio" },
    { q: "Pieza circular que gira sobre un eje", a: "rueda" },
    { q: "Conjunto de prendas textiles para vestir a diario", a: "ropa" },
    { q: "Aparato para saber la hora", a: "reloj" },
    { q: "Malla de hilos para pescar en el mar", a: "red" },
    { q: "Soberano coronado que gobierna una monarquía", a: "rey" },
    { q: "Soberana esposa del monarca en la corte", a: "reina" },
    { q: "Roedor pequeño de bigotes que roe en despensas", a: "raton" },
    { q: "Parte del árbol con hojas", a: "rama" },
    { q: "Local público donde se sirve comida al momento", a: "restaurante" },
    { q: "Contestación ajustada que resuelve una duda planteada", a: "respuesta" },
    { q: "Escritor mexicano del siglo veinte autor de El gallo de oro y Diles", a: "rulfo" },
    { q: "Articulación media de la pierna que permite doblarla", a: "rodilla" },
    { q: "Bloque mineral de gran dureza en montañas", a: "roca" },
    { q: "Árbol de bellotas con madera recia para toneles", a: "roble" },
    { q: "Color cálido de la sangre y la amapola", a: "rojo" },
    { q: "Juego de casino con bola", a: "ruleta" },
    { q: "Contacto leve entre superficies que deja marca", a: "roce" },
    { q: "Huella honda que deja el carro en tierra blanda", a: "rodera" }
  ],
  "S": [
    { q: "Dramaturgo inglés autor de Hamlet", a: "shakespeare" },
    { q: "Primera persona del plural del condicional simple del verbo ser", a: "seriamos" },
    { q: "Segunda persona del singular del pretérito imperfecto de subjuntivo del verbo cantar", a: "cantaras" },
    { q: "Primera persona del plural del condicional simple del verbo comer", a: "comeriamos" },
    { q: "Astro que da luz de día", a: "sol" },
    { q: "Asiento individual con respaldo para una persona", a: "silla" },
    { q: "Asiento largo y mullido del salón para descansar", a: "sofa" },
    { q: "Animal parecido a la rana", a: "sapo" },
    { q: "Escritor portugués contemporáneo autor de El hombre duplicado y Lucidez", a: "saramago" },
    { q: "Periodo de siete días de lunes a domingo", a: "semana" },
    { q: "Bosque tropical denso de vegetación enmarañada", a: "selva" },
    { q: "Grano fértil que origina una planta nueva", a: "semilla" },
    { q: "Cadena de montañas con picos alineados", a: "sierra" },
    { q: "Líquido corporal que impulsa el corazón por venas", a: "sangre" },
    { q: "Estado corporal sin enfermedad ni dolencia", a: "salud" },
    { q: "Dato oculto que se guarda bajo discreción", a: "secreto" },
    { q: "Libre de peligro y protegido contra daños", a: "seguro" },
    { q: "Instante breve tras el primero en el minuto", a: "segundo" },
    { q: "Animal que se arrastra sin patas", a: "serpiente" },
    { q: "Gesto alegre con la boca", a: "sonrisa" },
    { q: "Para la cabeza contra el sol", a: "sombrero" },
    { q: "Caldo caliente con verduras que se toma con cuchara", a: "sopa" },
    { q: "Pez marino pequeño que se enlata con aceite", a: "sardina" },
    { q: "Jornada previa al domingo para descansar", a: "sabado" },
    { q: "Viento cálido del desierto que trae polvo", a: "siroco" }
  ],
  "T": [
    { q: "Escritor ruso autor de Guerra y paz", a: "tolstoi" },
    { q: "Primera persona del plural del pretérito imperfecto de subjuntivo del verbo cantar", a: "cantaramos" },
    { q: "Segunda persona del singular del pretérito imperfecto de subjuntivo del verbo saltar", a: "saltaras" },
    { q: "Primera persona del plural del condicional simple del verbo votar", a: "votariamos" },
    { q: "Dulce de cumpleaños con velas", a: "tarta" },
    { q: "Instrumento que se toca con baquetas", a: "tambor" },
    { q: "Vehículo amarillo de alquiler con contador que marca el precio", a: "taxi" },
    { q: "Poeta bengalí universal autor de El jardinero y La luna nueva", a: "tagore" },
    { q: "Felino rayado de caza potente en la jungla", a: "tigre" },
    { q: "Recipiente pequeño con asa para café caliente", a: "taza" },
    { q: "Aparato de voz para hablar a distancia", a: "telefono" },
    { q: "Caja de imágenes que emite programas diarios", a: "television" },
    { q: "Sala con escenario para obras en directo", a: "teatro" },
    { q: "Parte alta de la casa", a: "techo" },
    { q: "Barra blanca de yeso para escribir en pizarra", a: "tiza" },
    { q: "Útil de dos hojas para recortar papel", a: "tijera" },
    { q: "Fruto carnoso de ensalada con jugo ácido", a: "tomate" },
    { q: "Reptil lento con caparazón que se esconde", a: "tortuga" },
    { q: "Vehículo largo sobre raíles con vagones unidos", a: "tren" },
    { q: "Tallo leñoso grueso que sostiene al árbol", a: "tronco" },
    { q: "Estruendo del rayo tras el relámpago", a: "trueno" },
    { q: "Parte del día antes de la noche", a: "tarde" },
    { q: "Deber escolar para practicar en casa", a: "tarea" },
    { q: "Planeta habitado con mares y continentes", a: "tierra" },
    { q: "Tela vaquera azul para pantalones resistentes", a: "tejano" }
  ],
  "U": [
    { q: "Escritor español autor de Niebla", a: "unamuno" },
    { q: "Tercera persona del singular del pretérito perfecto simple de poder", a: "pudo" },
    { q: "Tercera persona del plural del condicional simple del verbo subir", a: "subirian" },
    { q: "Primera persona del plural del condicional simple del verbo cruzar", a: "cruzariamos" },
    { q: "Fruto en racimo para mosto y mesa", a: "uva" },
    { q: "Escritor vasco contemporáneo autor de Bilbao Nueva York y Lo que mueve", a: "uribe" },
    { q: "Postrero en una serie que cierra el orden", a: "ultimo" },
    { q: "Que exige atención inmediata sin demora", a: "urgente" },
    { q: "Solo en su clase sin otro igual", a: "unico" },
    { q: "Vestido igual para todo un colectivo escolar", a: "uniforme" },
    { q: "Junta estable de dos partes en una", a: "union" },
    { q: "Centro superior de estudios con facultades variadas", a: "universidad" },
    { q: "Lámina dura al final del dedo", a: "uña" },
    { q: "Entrada baja de la puerta antes del interior", a: "umbral" },
    { q: "Ave blanca y negra que recoge brillos", a: "urraca" },
    { q: "Caballo fabuloso con un cuerno en la frente", a: "unicornio" },
    { q: "Tienda de comestibles finos de barrio", a: "ultramarinos" },
    { q: "Caja cerrada para depositar votos", a: "urna" },
    { q: "Quien utiliza un servicio con clave propia", a: "usuario" },
    { q: "Objeto manual de cocina para preparar guisos", a: "utensilio" },
    { q: "Nombre de la letra ve", a: "uve" },
    { q: "Puerta hospitalaria para casos graves inmediatos", a: "urgencias" },
    { q: "De segunda mano con previo dueño", a: "usado" },
    { q: "Que presta servicio práctico a diario", a: "util" },
    { q: "Cada una de las partes", a: "unidad" }
  ],
  "V": [
    { q: "Pintor español autor de Las Meninas", a: "velazquez" },
    { q: "Primera persona del plural del condicional simple del verbo vivir", a: "viviriamos" },
    { q: "Segunda persona del singular del condicional simple del verbo volver", a: "volverias" },
    { q: "Tercera persona del singular del condicional simple del verbo llover", a: "lloveria" },
    { q: "Animal que da leche y dice mu", a: "vaca" },
    { q: "Caldo de uvas fermentado en bodega", a: "vino" },
    { q: "Barco ligero movido solo por velas", a: "velero" },
    { q: "Recipiente para beber agua en la mesa", a: "vaso" },
    { q: "Abertura con cristal para ventilar la estancia", a: "ventana" },
    { q: "Estación calurosa de vacaciones y playa", a: "verano" },
    { q: "Color de la hierba y la esperanza", a: "verde" },
    { q: "Prenda de una pieza para ocasiones", a: "vestido" },
    { q: "Escritor francés decimonónico autor de Miguel Strogoff y El faro del fin", a: "verne" },
    { q: "Aire en movimiento que agita ramas", a: "viento" },
    { q: "Cilindro de cera con mecha", a: "vela" },
    { q: "Quien vive en la puerta contigua", a: "vecino" },
    { q: "Pinchazo preventivo contra virus e infecciones", a: "vacuna" },
    { q: "Coche remolcado del tren para carga", a: "vagon" },
    { q: "Hondonada entre montes con río", a: "valle" },
    { q: "Niebla caliente que sale de la olla", a: "vapor" },
    { q: "Lo cierto opuesto a la mentira", a: "verdad" },
    { q: "Pena íntima por una falta cometida", a: "verguenza" },
    { q: "Armario con cristal para exponer objetos", a: "vitrina" },
    { q: "Monte que arroja lava en erupción", a: "volcan" },
    { q: "Ir a ver a alguien", a: "visita" }
  ],
  "W": [
    { q: "Cineasta estadounidense director de Ciudadano Kane", a: "welles" },
    { q: "Tercera persona del singular del condicional simple del verbo wasapear", a: "wasapearia" },
    { q: "Primera persona del plural del pretérito imperfecto de subjuntivo del verbo wasapear", a: "wasapearamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de wasapear", a: "wasapearon" },
    { q: "Red de páginas de internet", a: "web" },
    { q: "Red inalámbrica doméstica para conectar móviles", a: "wifi" },
    { q: "Deporte en piscina con balón", a: "waterpolo" },
    { q: "Película del oeste con duelos y diligencias", a: "western" },
    { q: "Deporte con tabla y vela", a: "windsurf" },
    { q: "Sartén honda para saltear al estilo oriental", a: "wok" },
    { q: "Metal denso de filamentos que da luz", a: "wolframio" },
    { q: "Relativo al músico alemán autor del Anillo", a: "wagneriano" },
    { q: "Aparato para hablar a distancia", a: "walkie" },
    { q: "Tienda cónica india de pieles y palos", a: "wigwam" },
    { q: "Arte marcial chino de saltos acrobáticos", a: "wushu" },
    { q: "Programas informáticos que ejecutan el ordenador", a: "software" },
    { q: "Piezas físicas del ordenador que se tocan", a: "hardware" },
    { q: "Relativo a la capital estadounidense y su primer presidente", a: "washingtoniano" },
    { q: "Jinete del oeste con lazo y sombrero", a: "cowboy" },
    { q: "Tabla para deslizarse sobre nieve polvo", a: "snowboard" },
    { q: "Unidad de fuerza del sistema internacional", a: "newton" },
    { q: "Bocadillo de dos panes con relleno frío", a: "sandwich" },
    { q: "Capital federal estadounidense junto al Potomac", a: "washington" },
    { q: "Músico alemán autor del Anillo", a: "wagner" },
    { q: "Escritor irlandés victoriano autor de El fantasma de Canterville y De profundis", a: "wilde" }
  ],
  "X": [
    { q: "Historiador griego autor de la Anábasis", a: "xenofonte" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo explicar", a: "explicara" },
    { q: "Primera persona del plural del condicional simple del verbo examinar", a: "examinariamos" },
    { q: "Tercera persona del plural del pretérito perfecto simple de extraer", a: "extrajeron" },
    { q: "Prueba del cole con preguntas", a: "examen" },
    { q: "Deporte de cuadrilátero con guantes acolchados", a: "boxeo" },
    { q: "Instrumento dorado de viento para jazz", a: "saxofon" },
    { q: "Puesto ordinal tras el quinto en lista", a: "sexto" },
    { q: "Escrito breve para leer en voz alta", a: "texto" },
    { q: "Natural de otro país con pasaporte", a: "extranjero" },
    { q: "Café corto e intenso de máquina", a: "expreso" },
    { q: "Superficie alargada de terreno cultivable", a: "extension" },
    { q: "Parte de fuera de un edificio", a: "exterior" },
    { q: "Añadido de más sobre lo previsto", a: "extra" },
    { q: "Brazo o pierna articulada del cuerpo", a: "extremidad" },
    { q: "Vida fuera del país por destierro", a: "exilio" },
    { q: "Quien domina una materia por práctica", a: "experto" },
    { q: "Estallido con fuego y onda expansiva", a: "explosion" },
    { q: "Salida corta en grupo para conocer parajes", a: "excursion" },
    { q: "Pintor argentino vanguardista autor de Drago y Pan danza", a: "xul" },
    { q: "Gas vital que se respira del aire", a: "oxigeno" },
    { q: "Piso de dos alturas comunicadas", a: "duplex" },
    { q: "Mezcla de dos cosas distintas", a: "mixto" },
    { q: "Enlace que une dos ideas", a: "nexo" },
    { q: "Conjunto de voces de una lengua", a: "lexico" }
  ],
  "Y": [
    { q: "Poeta irlandés premio Nobel autor de La torre", a: "yeats" },
    { q: "Primera persona del singular del presente de subjuntivo de haber", a: "haya" },
    { q: "Primera persona del singular del presente de subjuntivo de ir", a: "vaya" },
    { q: "Tercera persona del plural del pretérito perfecto simple de oír", a: "oyeron" },
    { q: "Disciplina de estiramiento y respiración pausada", a: "yoga" },
    { q: "Barco recreativo blanco de lujo", a: "yate" },
    { q: "Núcleo amarillo del huevo central", a: "yema" },
    { q: "Lácteo batido de postre con fermentos", a: "yogur" },
    { q: "Equino hembra que cría potros", a: "yegua" },
    { q: "Polvo blanco para escayolar fracturas", a: "yeso" },
    { q: "Antiséptico pardo para desinfectar heridas", a: "yodo" },
    { q: "Raíz tropical comestible de guisos", a: "yuca" },
    { q: "Bloque de forja para golpear hierro", a: "yunque" },
    { q: "Mina rica bajo tierra con vetas", a: "yacimiento" },
    { q: "Juguete que sube y baja", a: "yoyo" },
    { q: "Pareja de bueyes para arar junta", a: "yunta" },
    { q: "Escritora francesa clásica autora de Opus nigrum y El tiro de gracia", a: "yourcenar" },
    { q: "Practicante avanzado de meditación corporal", a: "yogui" },
    { q: "Toro castrado de tiro pausado", a: "buey" },
    { q: "Fibra vegetal para sacos resistentes", a: "yute" },
    { q: "Natural del norte estadounidense actual", a: "yanqui" },
    { q: "Medida agraria de tierra labrada", a: "yugada" },
    { q: "Alimento cocinado para el mediodía", a: "yantar" },
    { q: "País arábigo del sur peninsular", a: "yemen" },
    { q: "Primera voz del verbo ser en presente", a: "soy" }
  ],
  "Z": [
    { q: "Escritor francés autor de Germinal", a: "zola" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo cruzar", a: "cruzara" },
    { q: "Primera persona del plural del condicional simple del verbo gozar", a: "gozariamos" },
    { q: "Tercera persona del singular del pretérito imperfecto de subjuntivo del verbo empezar", a: "empezara" },
    { q: "Jugo exprimido de naranja natural", a: "zumo" },
    { q: "Animal astuto de cola grande", a: "zorro" },
    { q: "Arbusto espinoso de moras silvestres", a: "zarza" },
    { q: "Calzado para proteger los pies", a: "zapato" },
    { q: "Díptero nocturno de picadura fina que zumba junto al oído", a: "zancudo" },
    { q: "Corte largo en la tierra para drenar", a: "zanja" },
    { q: "Oficio que repara calzado en taller", a: "zapatero" },
    { q: "Obra lírica española con canto y diálogo", a: "zarzuela" },
    { q: "Recinto con animales para visita pública", a: "zoologico" },
    { q: "Calzado rústico de madera entera", a: "zueco" },
    { q: "Ruido continuo de abeja en vuelo", a: "zumbido" },
    { q: "Quien usa la izquierda por destreza", a: "zurdo" },
    { q: "Nombre de la última letra", a: "zeta" },
    { q: "Línea quebrada en ángulos alternos", a: "zigzag" },
    { q: "Gema azul de joyería valiosa", a: "zafiro" },
    { q: "Raíz naranja de ensalada y guiso", a: "zanahoria" },
    { q: "Parte baja de la pared", a: "zocalo" },
    { q: "Persona torpe y lenta de movimientos", a: "zoquete" },
    { q: "Escritor austríaco de entreguerras autor de Momentos estelares y Piedad", a: "zweig" },
    { q: "Chaqueta rústica de piel con lana", a: "zamarra" },
    { q: "Pendiente que cuelga del lóbulo", a: "zarcillo" }
  ]
};
